### ISSUE TITLE
Settings format (Windows)

### ISSUE THREAD

**Issue by Tigger1** [ZencashOfficial/arizen#100]
Testing was done on: Windows
Arizen version: 1.0.0

It would be more user friendly to use better format, see picture with a red rectangle bellow.
![9](https://user-images.githubusercontent.com/32774850/31861422-567c5802-b72d-11e7-81d8-fd8a54357109.png)

The address isn't shown in whole format however there is big space for that. See a red rectangle in the picture below.
![10](https://user-images.githubusercontent.com/32774850/31861494-6d2f44be-b72e-11e7-8318-b1acdbc5dbfe.PNG)

**Comment by neduchal** [comment]
Changed in PR #101

**Comment by LukasBures** [comment]
solved
