### ISSUE TITLE
Cut/copy/paste does not work

### ISSUE THREAD

**Issue by madsb** [ZencashOfficial/arizen#110]
Testing was done on: macOS High Sierra
Arizen version: 1.0.0

Cut/copy/paste does not work on Login screen and Create Wallet screen.

**Comment by jiri-novotny** [comment]
@LukasBures please test
OS: Win 10 is OK

**Comment by LukasBures** [comment]
Yes, it doesnt work. You have to write your password once again, not just copy/paste.

**Comment by LukasBures** [comment]
Solved in 0284a4a2010bb7ef9129c368694534b9e1ac26c4
