### ISSUE TITLE
Special characters in username

### ISSUE THREAD

**Issue by LukasBures** [ZencashOfficial/arizen#113]
OS: Windows 10
Version v1.0.0

From Slack:
Arizen doesn't like when we put special char in the usernam. I've put "Cédric" for username but it fail when login so I had to create new wallet with cedzzz as username. Now it works.

**Comment by Tigger1** [comment]
Tested on Windows 7
Version v1.0.0

Issue confirmed. Special characters are not accepted (neither if it is Wolverine :-D). Please, see picture bellow:
![24](https://user-images.githubusercontent.com/32774850/32133992-c6ad63ae-bbe3-11e7-8af9-072b43991bac.PNG)

**Comment by woky** [comment]
Fixed in 9d25f24b

**Comment by LukasBures** [comment]
closed
