### ISSUE TITLE
[RFC] storage change

### ISSUE THREAD

**Issue by woky** [ZencashOfficial/arizen#115]
Currently, we're using SQLite to store state and cached data. I propose we ditch that in favor of simpler JSON file storage. I haven't considered versioning and migration, which we will need for upgrades and imports from older storage formats, yet.

## Reasons for change
We do not use nor need features of a SQL databases at all.
- We don't need concurrent access to the database. In fact, we don't even have it now because we use in-memory database and if we start and use multiple instances of Arizen, each will silently overwrite the encrypted database file which could and probably will lead to data loss (for example when you create a new private key in the first instance, send money to it, close the first instance, then close the second instance, then you'll lose the private key (and money) from the first instance because the second instance overwrites the encrypted database file on exit). This could be prevented by using a lock file and not allowing to run multiple instances of Arizen on one computer. The point is, we don't need to concurrently modify the database file because we want it to be used only from the main process of a single Arizen instance.
- We don't need SQL. First of all, transactions are immutable. Once we load them from the database we send them to the render process and that's all. In the main thread, we only need a set of known transactions IDs and addresses to fetch new transactions which we'll then save and send to the render thread. Possible sorting and searching of transactions will be done on a list of JavaScript objects in the render thread without SQL. So we don't need to keep the transactions in the main thread. But currently we keep the whole database in the memory for no valid reason. Second, it's unnecessarily unpleasant to work with SQLite via `sql.js`. See for example [this callback](https://github.com/ZencashOfficial/arizen/blob/98bf7b284bf398e961223deb05785a6f02c021da/app/wallet.js#L206) which is passed `sql.js` result object. Why do we have to work with shit like `data.wallets[i][4]` instead of `data.wallets[i].balance`? Can't we just use plain JavaScript objects? What advantage does SQL brings us here when the code is less readable and the data stay in the memory in the end anyway!?

## Rough idea
We will have two compressed and then encrypted JSON files in Arizen state directory (`${walletname}` refers to an user's wallet name):
- **private** - `${walletname}.private.dat`
  - Will contain
    - *master* private keys
    - optional user supplied names for *master* private keys (addresses)
    - (in future) BIP-32 structure
    - Arizen settings (API URL, etc.)
  - We don't need to store addresses as they can be derived in run time.
  - Will be updated in *blocking fashion* every time a change is made to the wallet.
- **cache** - `${walletname}.cache.dat`
  - everything what can be read from the blockchain (last known balance and transactions for each private key or derived address)
  - Once it is read and processed it'll be discarded.
    - New transactions and changed balances will be kept in a queue.
    - The queue will be saved to the file every N minutes.

This is just a rough idea without any specifics. Comments?

**Comment by LukasBures** [comment]
Will be implemented in #72

**Comment by zennermac** [comment]
I am closing this out now as a won't do, as Sphere By Horizen is now available.
