### ISSUE TITLE
Arizen on Ubuntu suggestion and bug.

### ISSUE THREAD

**Issue by romali** [ZencashOfficial/arizen#117]
Dangerus!
Creating a new wallet with the name of already existing wallet name overwrite .awd file and create a new entry in users.arizen file, after that it is not possible to log in to this wallet.

Bug:
Import wallet on Ubuntu from .awd/.uawd not working, timestamp on wallet.awd file it's changing, but size stay the same, (sqlite-3.8.2-1ubuntu2.1)

Suggestion:
Possibility of importing a wallet just after start program, right now is only possible after create a new wallet, then login into it and import.

**Comment by LukasBures** [comment]
Thank you for testing! We are working on it!

**Comment by jiri-novotny** [comment]
fixed in #118 
@LukasBures check mac
@neduchal check linux

**Comment by LukasBures** [comment]
@Tigger1 test it please too

**Comment by LukasBures** [comment]
"dangerous" fixed for v1.0.1
"bug" - try it once again please in v1.0.1
"suggestion" - importing functionality was improved in v1.0.1
