### ISSUE TITLE
Mac Password Issue

### ISSUE THREAD

**Issue by Tejeni** [ZencashOfficial/arizen#124]
I downloaded the wallet and installed it on OS X Open Sierra and tried to create an account in the wallet..  I used a long password in excess of 30 characters random complex character which meet all the criteria.  The wallet and account was created it seems but it crashed every time I tried to load the account.  I also tried to import the swing wallet without perceived success when I created this account. The path to wallet read with a fake wallet path in the directory listing.  I am not sure if this has anything to do with the crashing issue or not.  However, The zen wallet crashes after I click login and the account does exist on the computer because I could not use the same account name when I tried to remake the account with the same username..  

I also create an account using a different username and used 9 character complex password and the wallet created and loaded normally.

**Comment by LukasBures** [comment]
Thank you for the testing.

- `wallet.dat` import is not supported (there is no way how to extract all addresses from `wallet.dat` to any of javascript wallets now), only `awd` or `uawd`
- creating new account with already existed username is prohibited (it prevents users to overwrite their account and lose ZEN)
- fake-path is normal, that is on every platform

So only bug here is that long password is issue.

**Comment by jiri-novotny** [comment]
win 10
user: bbb
pass: &*er;B~~v/"5Hj/aSpW?WLXZ{=%HNvCwc~Fy{pU=,${(8[vt>,B55sJg[AchSG:B
pass is 64 random chars and account is ok

**Comment by Tejeni** [comment]
Lukas,

Is there any way I can delete out the accounts I created on my Mac and
recreate the wallets from scratch.

I don't have any zen in the Arizen wallet yet and I would like to make sure
keep the user name and password of my choosing.

What are the current hard limits on password length?

Also where do I need to go backup my Arizen wallet so I can make sure I
backup all my important keys in case I ever need to do a restore or deploy
on multiple pcs.

Thanks,

David

**Comment by LukasBures** [comment]
If you dont have any accounts with any ZENs, then you can go to: `~/Library/Application Support/Arizen` and delete `users.arizen` and all in `wallets` folder.

**Comment by LukasBures** [comment]
And as @jiri-novotny experimented, 64 characters should be OK

**Comment by LukasBures** [comment]
And for backups use:

![backups](https://user-images.githubusercontent.com/3979946/32385422-598faa4a-c0be-11e7-95fc-c12f281459a5.png)

**Comment by LukasBures** [comment]
Marked as solved, reopen it when not.
