### ISSUE TITLE
Doubled history entries, ver 1.0.1

### ISSUE THREAD

**Issue by ToLive** [ZencashOfficial/arizen#127]
Hi!

After update to 1.0.1:
1. All my previous was wiped. Not a big deal, but in options I set it to store 250 entries.
2. Transactions in history doubled. See screenshot.
![arizen_2017-11-05_20-03-27](https://user-images.githubusercontent.com/2019736/32415016-cfe569a8-c264-11e7-8fc7-ed02ab602999.png)

**Comment by jiri-novotny** [comment]
Is this one-time issue or every time you log in?

**Comment by ToLive** [comment]
> Is this one-time issue or every time you log in?
Every time I login.
![arizen_2017-11-06_09-54-04](https://user-images.githubusercontent.com/2019736/32423375-9a660962-c2d8-11e7-92fc-d7453ff02a67.png)

**Comment by jiri-novotny** [comment]
Have you updated from 0.1.0 or 1.0.0?

**Comment by ToLive** [comment]
From 1.0.0

**Comment by LukasBures** [comment]
Thank you for testing, in next version it will be solved.
