### ISSUE TITLE
Problem send ZEN from Arizen on Linux

### ISSUE THREAD

**Issue by romali** [ZencashOfficial/arizen#130]
Couple of times I send zen without the problem but now is not working anymore
After pressing "send now" button Arizen become grey and this is expected but after while returns following message:
`Error:
bhash_err: Error: socket hang up
`
And here output from command line:

> me@pc:~$ arizen 
> Update for linux-x64-prod-v1.0.1 is not available
> { Error: socket hang up
>     at TLSSocket.onHangUp (_tls_wrap.js:1130:19)
>     at Object.onceWrapper (events.js:314:30)
>     at emitNone (events.js:110:20)
>     at TLSSocket.emit (events.js:207:7)
>     at endReadableNT (_stream_readable.js:1045:12)
>     at _combinedTickCallback (internal/process/next_tick.js:138:11)
>     at process._tickCallback (internal/process/next_tick.js:180:9)
>   code: 'ECONNRESET',
>   path: null,
>   host: 'explorer.zensystem.io',
>   port: 443,
>   localAddress: undefined }

**Comment by romali** [comment]
I noticed that Arizen is trying establish connection with 104.27.3.80, but no luck.

> tcp        0      0 10.0.1.10:39127         104.27.3.80:443         TIME_WAIT  
> tcp        0      0 10.0.1.10:42757         104.27.2.80:443         TIME_WAIT  
> tcp        0      0 10.0.1.10:39129         104.27.3.80:443         TIME_WAIT  
> tcp        0      0 10.0.1.10:39101         104.27.3.80:443         TIME_WAIT  
> tcp        0      0 10.0.1.10:42750         104.27.2.80:443         TIME_WAIT  
> tcp        0      0 10.0.1.10:39102         104.27.3.80:443         TIME_WAIT  
> tcp        0      0 10.0.1.10:39117         104.27.3.80:443         TIME_WAIT  
> tcp        0      0 10.0.1.10:39121         104.27.3.80:443         TIME_WAIT  
> tcp        0      0 10.0.1.10:42771         104.27.2.80:443         TIME_WAIT  

.....

**Comment by jiri-novotny** [comment]
can you try different explorer with insight api?
e.g.
explorer http://explorer.zenmine.pro/insight/
api http://explorer.zenmine.pro/insight-api-zen/

**Comment by romali** [comment]
Yes is working, but is not secure connection http, Actually I was looking for another explorer url but was unable to find.

**Comment by LukasBures** [comment]
Has been solved.
