### ISSUE TITLE
Wallet address now showing sent zen on Mac client.

### ISSUE THREAD

**Issue by Tejeni** [ZencashOfficial/arizen#133]
I sent zen from my swing wallet to by Arizen wallet to four different address and the zen never arrived in my my Arizen wallet, even though more than an hour passed since I have sent the zen to the Arizen wallet.  What do I have to do to make sure the Arizen wallet reflects the transactions did occur and makes the balances available to me.  I see the transactions did occur and were updated on the block chain.  Below is the link to the specific address I sent my zen to.  What must I do to update my Arizen wallet to show the zen has been properly transferred so the funds are available to me?

Below is the addresses I sent the zen to in my Arizen wallet.

http://explorer.zenmine.pro/insight/address/znazdKQdnVWj3xKLrFtWT8anEyMjc8a3NBS
http://explorer.zenmine.pro/insight/address/znWdeZz8YGgcRZoxMwWmAuEmreRFTx6wtL4
http://explorer.zenmine.pro/insight/address/znjckuLgGmuWxHFYCGZN3m1RpSwaQVGPwBr
http://explorer.zenmine.pro/insight/address/znjNbExyE28KM1ug3spKmrHVTBJWHyJr7yS

Please help!

Thanks,
David

**Comment by LukasBures** [comment]
Hey David,

what version of Arizen do you have? Check it in About menu.

Then go to Settings and check your settings your Explorer and API addresses: 
![68747470733a2f2f692e696d6775722e636f6d2f4362744f714e632e706e67](https://user-images.githubusercontent.com/3979946/33067837-b84b3942-ceaf-11e7-940a-f3c7d819f063.png)

Save your setting, restart Arizen and let me know.

Lukas

**Comment by Tejeni** [comment]
I am using version Arizen version: 1.0.1.

I have changed the history setting to 150 items and then clicked saved.

I reopened the wallet and the zen appears to be credited to the addresses.

Thank you for your quick response, I was getting nervous for a while that I had lost my funds.

Best Regards,

David

**Comment by LukasBures** [comment]
👍 

solved, closing
