### ISSUE TITLE
Feature Request: Import Wallets from private Keys

### ISSUE THREAD

**Issue by pedrosimao** [ZencashOfficial/arizen#141]
I have a paper wallet which I want to import into Arizen. But there is no option to import Private Key.
Also when I try to import from wallet.dat created by zencash wallet, the app simply crash.

**Comment by jiri-novotny** [comment]
Hi we are working on private key import.
wallet.dat format is not supported

**Comment by pedrosimao** [comment]
Ok, thanks a lot for your answer!

**Comment by LukasBures** [comment]
It will be in next version (not in version v1.1.0)

**Comment by pedrosimao** [comment]
Hello,
Now we have version v1.1.1, but I didn't see the feature allowing to import PrivateKeys yet.

**Comment by LukasBures** [comment]
You are right, but sadly, v1.1.1 is only bug fix. Bigger features pack will come in January.

**Comment by LukasBures** [comment]
has been implemented here - #199

close
