### ISSUE TITLE
Install help

### ISSUE THREAD

**Issue by firsttubr** [ZencashOfficial/arizen#143]
I'd like to install Arizen on my Linux mint machine.  I cloned the repo to my hard drive, now I see an /arizen folder.  What do I do now?
I'm a newbie with installing from github.
Thanks!

**Comment by firsttubr** [comment]
I downloaded the appImage file.  When I run it it prompts me for a new user name and password, then when I click create wallet it is looking for a file, but I don't have a wallet yet. What am I doing wrong?
thanks

**Comment by AndreiD** [comment]
what you are doing wrong, is asking for help where no one gives a shit about you and your problems 🤑 
I have the same problem....

**Comment by neduchal** [comment]
Hi, I can't reproduce your error now. Everything is OK on Ubuntu 16.04.

Here is short description of registration process: 
Run appImage for the firs time (no directory ~/.arizen in your home folder) --> The registration screen will shown. Then you have to fill username and both password inputs and click on Create wallet (without choosing any wallet file --> it is only for importing old wallet) --> New wallet is created. And then you can login with chosen username and password. 

Did you do it same way? Can you upload a screenshot of the bad beahviour of the app?

**Comment by LukasBures** [comment]
no response - close
