### ISSUE TITLE
No Linux Support - Windows Install Blocked by anti-virus Avast

### ISSUE THREAD

**Issue by tbrone** [ZencashOfficial/arizen#145]
I run Linux Mint 18 on my primary machine.  Arizen does not contain a Linux package.  Will one be developed?

Using a Windows 10 machine, I downloaded Arizen.Setup.1.1.1.exe.  Installation was blocked by my anti-virus due to a FileRepMalware warning.  

Can you recommend an alternative?

**Comment by LukasBures** [comment]
Arizen-1.1.1-x86_64.AppImage file = Linux package

**Comment by LukasBures** [comment]
Which antivirus are you using?

**Comment by cheetahfm** [comment]
@LukasBures Look here results for Arizen.Setup.1.1.1.exe: [virustotal](https://www.virustotal.com/#/file/2c3416baab410b48525a5311224025ed9807802752e5bc790741f4bbf440b711/detection)

**Comment by LukasBures** [comment]
If Linux support is solved for you I will close this. About false positive virus scanner alert we can continue in #153

**Comment by tbrone** [comment]
I am using Avast anti-virus.  I see that it is one of two that returns a false positive.  I will try the Arizen-1.1.1-x86_64.AppImage file.

**Comment by tbrone** [comment]
I was able to install the AppleImage file on Linux Mint.  Thank you.  Both issues may be closed, since I will not be using the Windows version.  Thanx again!

**Comment by LukasBures** [comment]
close
