### ISSUE TITLE
QR code - option for export to the pdf file

### ISSUE THREAD

**Issue by Tigger1** [ZencashOfficial/arizen#149]
Testing was done on: Windows
Arizen version: 1.1.1

If the user wants to deposit, it can be used QR code. It would be nice to have an option for of export QR code to the pdf file.

![cervena nula](https://user-images.githubusercontent.com/32774850/34119943-36f77416-e424-11e7-96e7-5b84779cac79.png)

**Comment by woky** [comment]
Fixed in #209
