### ISSUE TITLE
Total balance in another currencies

### ISSUE THREAD

**Issue by Tigger1** [ZencashOfficial/arizen#150]
Testing was done on: Windows
Arizen version: 1.1.1

It would be nice to have the total balance in EUR, USD or RUB (Russian ruble) with the date of update.

![penezenka_front](https://user-images.githubusercontent.com/32774850/34120338-8f9afa74-e425-11e7-978d-fbb9274fea70.png)

**Comment by LukasBures** [comment]
#158

**Comment by LukasBures** [comment]
implemented
