### ISSUE TITLE
Logo position

### ISSUE THREAD

**Issue by Tigger1** [ZencashOfficial/arizen#151]
Testing was done on: Windows
Arizen version: 1.1.1

The logo isn't in the middle of screen. It would be nice to have it in the middle:-)

![logo_bug](https://user-images.githubusercontent.com/32774850/34120916-920546aa-e427-11e7-9667-feb223eee68b.png)

**Comment by LukasBures** [comment]
@neduchal take a look please.

**Comment by neduchal** [comment]
Logo position corrected in PR #200

**Comment by LukasBures** [comment]
Solved.
