### ISSUE TITLE
False positive virus scanner alert

### ISSUE THREAD

**Issue by Tigger1** [ZencashOfficial/arizen#153]
It's known that 2 antivir SW are detecting false positive alert of our Win version installation file, see [link](https://www.virustotal.com/#/file/2c3416baab410b48525a5311224025ed9807802752e5bc790741f4bbf440b711/detection) or picture below.

Solution - for being sure you can check sha256sum, if that it's identical with provided one from released section then it's fine.

![antivir](https://user-images.githubusercontent.com/32774850/34123561-4a90c656-e430-11e7-9243-2f39e4decd3f.PNG)

**Comment by LukasBures** [comment]
Connecting this #145

**Comment by hthomp1** [comment]
found same in Norton for 1.1.1.  Turned off anti-virus for and still can't get it onto Windows 10.

**Comment by LukasBures** [comment]
Please, @woky @neduchal @Tigger1 please treat this as the most important thing.

I think this issue has started in version v1.1.1 - so the problem could be in updater npm package or I have no idea now.

**Comment by woky** [comment]
Reported

  https://github.com/ZencashOfficial/arizen/releases/download/v1.1.1/Arizen.Setup.1.1.1.exe

as false positive to Avast.

**Comment by LukasBures** [comment]
Thank you

**Comment by LukasBures** [comment]
We have manually tested:
malwarebytes - ok
spyboost - ok
avast smart security - ok
kaspersky - ok
zonealarm - ok
comodo int sec pro - ok
mcafee  av - ok

--------------------------------------------
AVAST, NORTON and AVG are problematic:


![arizen_av_poblem_avast](https://user-images.githubusercontent.com/3979946/34353533-02c21bfa-ea29-11e7-90c0-8f98f902f648.png)
![arizen_av_poblem_avg](https://user-images.githubusercontent.com/3979946/34353535-0533d2de-ea29-11e7-8309-b561c4354f61.png)
![arizen_av_poblem_norton](https://user-images.githubusercontent.com/3979946/34353536-06bf46ce-ea29-11e7-9693-ff70308b6ff2.png)


Thank you MedaR for report

**Comment by woky** [comment]
I'd be glad if someone with Google-fu better than mine could point me to a definition of FileRepMalware. I can only find _How to remove FileRepMalware_, _Halp, my game won't launch_, etc.

Least meaingless resources I found:
https://github.com/arkypita/LaserGRBL/issues/176
https://msdn.microsoft.com/en-us/library/windows/desktop/dd323325

I also uploaded the installer to Avsat FTP as per https://support.avast.com/en-us/article/229/

**Comment by LukasBures** [comment]
The new version seems clear:

[MacOs](https://www.virustotal.com/#/file/fbdff1fc8ac826116ad0860bf311e923c041877c1d5c0e227ecf12451205b9ed/detection)

[Windows](https://www.virustotal.com/#/file/3532ec84d8bc6c4a6d4bff61de86ab9603ab3962b3a59c4d3a41567336b1c6f6/detection)

**Comment by neduchal** [comment]
Version 415ea5c seems clear on Linux too 

[Linux](https://www.virustotal.com/#/file/3a2a485bd0e39509b83c934895afc8ece3ef4863555ad4e1af34d398886ac3f5/detection)

**Comment by woky** [comment]
Arizen v1.1.2 seems fine on Windows 10 with both AVG and Avast:

![](https://i.imgur.com/VleRplj.png)
![](https://i.imgur.com/kIhd8gu.png)

**Comment by LukasBures** [comment]
fixed
