### ISSUE TITLE
Withdraw - default Error in incorrect form

### ISSUE THREAD

**Issue by Tigger1** [ZencashOfficial/arizen#154]
Testing was done on: Windows 7 Professional
Arizen version: 1.1.1

If you click on Withdraw then there is a default Error... Maybe it'd rather be better to change the error and say the same thing in different way. E.g. Please, fill the field "From" etc.
![withdraw2](https://user-images.githubusercontent.com/32774850/34173974-9a2a7f96-e4f7-11e7-86d0-17b382e8feea.png)

**Comment by LukasBures** [comment]
Fixed
