### ISSUE TITLE
Paper wallet

### ISSUE THREAD

**Issue by LukasBures** [ZencashOfficial/arizen#156]
#152 
  
- [ ] Do not show QR codes if user generated 3-4 wallets without reloading app. When I close the dialog using the X button, everything is fine. If I use the escape button in the keyboard, the next wallet generation fails to load qr codes.

**Comment by neduchal** [comment]
Paper wallet dialog design update in PR #200

**Comment by LukasBures** [comment]
reopen it when needed for solving bug in description.
