### ISSUE TITLE
where did my wallet go???

### ISSUE THREAD

**Issue by philbert** [ZencashOfficial/arizen#159]
I recently installed the Zencash wallet and bought some Zencash and transferred it to my wallet. I left the application running for a few days and it all seemed to be there and everything seemed to be fine.

Now all of the sudden the wallet says:
Username:
Password:

What is this? I don't ever remember creating a login for my wallet???!!

Or it gives me the option to create a new wallet!

Please tell me I still have the wallet on my computer somewhere?!

FYI using version 1.1.1 of Arizen on MacOS High Sierra

**Comment by Tigger1** [comment]
Hello philbert,

thank you for your question.

You had probably installed [swing wallet](https://github.com/ZencashOfficial/zencash-swing-wallet-ui). A there is no password. On the other hand in Arizen there is a Username and Password at the beginning as you can see on a picture below:
![login](https://user-images.githubusercontent.com/32774850/34246053-43b49e76-e62d-11e7-8255-1a5eba70c1c2.png)

Swing wallet and Arizen are different apps and have incompatible data files. Swing wallet uses _*.dat_ files. And Arizen uses _*.uawd_ (uncrypted Arizenwallet database) and  _*.awd_ (Arizen wallet database) files.

Please, let me know, if this advice doesn't help you.
Have a nice day:-)
Tigger1

**Comment by philbert** [comment]
I'm using the Arizen wallet.
Where is the wallet file stored on a mac?

**Comment by philbert** [comment]
I found it in /User/philbert/Library/Application Support

Thankfully the wallet file name jogged my memory what my username was!

Please do something to improve the usability of the wallet and warn users how to keep their wallet safe! Coming from the Bitcoin and Ethereum space I'm used to multi-word pass phrases, so this was outside my level of familiarity. 

I honestly didn't know what I was getting myself into and by the time the wallet decided to automatically lock itself, I had completely forgotten what I had done to create it!

**Comment by lojctapc** [comment]
I installed Arizen wallet and transferred my ZenCash there.  About one week ago, my WIN 10 system rebooted and now after login, my address is not showing, nor are my coins.  My address exists still when I go here:  https://explorer.zensystem.io/address/

Please help me figure out how to recover my coins.  Thank you.
