### ISSUE TITLE
export / import the wallet for backup

### ISSUE THREAD

**Issue by helxsz** [ZencashOfficial/arizen#161]
I want to have the feature that we can export the wallet to the local computer for the backup, or import the wallet to another computer easily. Exported or imported format could be in json.

**Comment by Tigger1** [comment]
Hello helxsz,

thank you for your feedback. We've already implemented export / import as you can see on picture below. For better info, please check out out brief [manual](https://github.com/ZencashOfficial/arizen/releases/tag/v1.1.1) named as Arizen.v1.1.1.Wallet.User.Manual.pdf. In the future we're not planning to support JSON.

And for the future communication I would recommend you to express yourself in more polite way. Please note that we aren't slaves.

Happy holidays,
Tigger1

![file](https://user-images.githubusercontent.com/32774850/34311695-49c8d9ca-e75f-11e7-8e75-e9e0d359ab89.png)

**Comment by helxsz** [comment]
Sorry for my words, I don't mean to be rude, you misunderstood me. I will add  " please could you implement this feature" next time,
