### ISSUE TITLE
32 bit

### ISSUE THREAD

**Issue by oscarwu1991** [ZencashOfficial/arizen#164]
Hi, anyway you can release a 32 but windows app? I want to install it on my local tablet. 

Thanks

**Comment by oscarwu1991** [comment]
Got an install issue and I assumed it is 32 but and 64 but issue. Please clairify

**Comment by LukasBures** [comment]
Hello - Sorry we are not planning to support mobile devices like tablets and etc. (not now).

**Comment by oscarwu1991** [comment]
Hi, tablet version I mean windows 10 tablet running atom processor. I was trying to install but got an installation error. I suspected it is caused by 32bit/64bit issue but can not confirm. Is the app 64 bit only?

Thanks

**Comment by Tigger1** [comment]
Hello oscarwu1991,

thank you for your question.

I regret to tell you that our app is only 64 bit. Currently we aren't planning to release 32 bit version. I'm very sorry.

Have a beautiful day:-)
Tigger1
