### ISSUE TITLE
Created adresses disapear. With their balances

### ISSUE THREAD

**Issue by yvuhk85** [ZencashOfficial/arizen#169]
Hi,

Got Arizen 1.1.1 installed, and created a new address via the Overview --> Get a new address button. Mined for a few days, went to check the balance today and found a zero balance. Also, the address i created (and which i mined to) is nowhere to be found. 

Went to check on explorer.zensystem.io and the address exists and has the expected balance.

How can I get back the adress ( I have not backed up the wallet)?

**Comment by lojctapc** [comment]
Experiencing same issue on Win 10 after recent MS update 12.26.17

**Comment by Decap1tator** [comment]
I experience this issue today. I created an address and then arizen crashed (I think, it wasn't open and I didn't close it.) When I reopened the wallet, the address that I had created had disappeared. I didn't lose a lot but had I not caught it when i did I would of lost a few weeks of effort.

**Comment by LukasBures** [comment]
If you don’t have any log, I can’t help you so much. Arizen doesn’t any log by default - because of privacy.

I can recommend you: create wallet, use one of default/zero addresses (or create new empty) close arizen, backup wallet file via backup functionality (RTFM) and then start to mine there for example.

**Comment by yvuhk85** [comment]
It's disappointing. If there is even a tiny risk of having addresses that vanish with no freaking way of retrieving them, then how do you not make it mandatory to create a back up in the install process? How do you accept that kind of failure from the software to begin with?!  It was my test and i lost 4 zen. I would have contributed to the development and given to the team.... instead my zen are stuck in an address that i can't access thanks to your stupid software

**Comment by Bjoern** [comment]
I also seem to be affected by this bug. I had only tested with a ZenCash faucet, so no huge damage done. But trust is an issue now. No log - can you enable logging somehow?

**Comment by LukasBures** [comment]
fixed 36d0ca2a31a6255f08910b0dc4a1d6d887494cf2

**Comment by yvuhk85** [comment]
It's fixed but my 4 zen are gone forever, right?
