### ISSUE TITLE
Can't log in conection refused.

### ISSUE THREAD

**Issue by SlickWhilly** [ZencashOfficial/arizen#171]
yesterday I logged in just fine and it took my money now I can't log in.  What gives?
I chose http://Eugene.Iotasupport.com

I am one day into the IOTA craze and thinking about writing it off as a hoax.  Reliable, secure, do you guys even know what those words mean?

Please help.

**Comment by LukasBures** [comment]
This is ZEN and its wallet Arizen not IOTA.
