### ISSUE TITLE
Crashing at login

### ISSUE THREAD

**Issue by Reeebuuk** [ZencashOfficial/arizen#175]
Hi guys,

first time downloading Arizen on Mac. v.1.1.1
Created an account and added a path to my wallet.dat file.

Then login screen appeared, after I enter my data the wallet just crashes. No errors or nothing. Gone :)

**Comment by LukasBures** [comment]
Sorry, but `wallet.dat` file is not supported. Arize uses another storing formats, that is why is Arizen the only one wallet which has encrypted locally stored files. Just let it blank and create empty new wallet or use supported files (if you have any previously created and backuped Arizen file) `.uawd` and `.awd`.

**Comment by Reeebuuk** [comment]
Can we have an error message which will say exactly that? :)

**Comment by LukasBures** [comment]
Yes, sure, we will add it.

**Comment by Reeebuuk** [comment]
Great, thx!
