### ISSUE TITLE
Portuguese translation

### ISSUE THREAD

**Issue by LukasBures** [ZencashOfficial/arizen#183]
See #173 for details

**Comment by piraz** [comment]
Can I add pt and pt_BR separated here?

They are kind of different and can get the the user kind of uneasy about a word.

**Comment by LukasBures** [comment]
Hey, please wait, we are working on our framework, and we would be happy if there will be all strings which have to be translated. If your language is not Portuguese - please use this #190 for Others language. 

Thank you

**Comment by piraz** [comment]
I'm Brazilian.

**Comment by felipemmachado** [comment]
I'm also able to help with portuguese.
+1 to differ pt and pt-br

**Comment by piraz** [comment]
Hey @felipemmachado, could you please go and review/modify piraz/arizen@daddaf14166ce71bb704b878c752cffe4e3d5958?

Second opinion/suggestions would be great.

**Comment by felipemmachado** [comment]
Sure!

**Comment by neduchal** [comment]
Hi guys, 
lang files will be extended in PR #196 (translation of new features available in version 1.1.2). They will be prepared for translation of login, create wallet pages. Please look at it and extend your translation.

**Comment by piraz** [comment]
What is the due date of code freeze?

**Comment by neduchal** [comment]
With the highest probability, it will be between next wednesday (10.1.) and friday (12.1. ). We will announce you the exact date after all new features will be finished and merged.

**Comment by sdaylor** [comment]
Portuguese translation in #232
