### ISSUE TITLE
Russian translation

### ISSUE THREAD

**Issue by LukasBures** [ZencashOfficial/arizen#185]
See #173 for details

**Comment by saintolexiy** [comment]
Ready, just not sure if I pulled request properly. Check please. PR #218
Also, here is a copy of the code:
[lang_ru.txt](https://github.com/ZencashOfficial/arizen/files/1620243/lang_ru.txt)

**Comment by LukasBures** [comment]
Thank you very much. We will wait up to 4 days and if nobody will have any adjustment we can merge this, then I will ask you for your T address.

**Comment by LukasBures** [comment]
Please see the main issue for information about the bounty.
