### ISSUE TITLE
French translation

### ISSUE THREAD

**Issue by LukasBures** [ZencashOfficial/arizen#189]
See #173 for details

**Comment by slauzon1** [comment]
If you ever need help in the French translation i can help :)

**Comment by slauzon1** [comment]
Actually is this still open, pretty new to this system. Sorry for the dumb question lol and part of my understanding is that I would need to do a pull request. Was it done by neduchal this time? Thanks for your time. Merci ;)

**Comment by sdaylor** [comment]
Added French translation in #230

**Comment by Kernel4** [comment]
Added French translation in #230

**Comment by raphaelbadia** [comment]
@sdaylor 's translation looks like it has been done with google translate. Bad punctuation and weird words (`tabWidthdraw: { label: "Se désister" `???)
@Kernel4 's translation looks better but still has many typos. Missing accents, bad punctuation and some letters are missing.

**Comment by LukasBures** [comment]
Please see the main issue for information about the bounty.
