### ISSUE TITLE
Others language translations

### ISSUE THREAD

**Issue by LukasBures** [ZencashOfficial/arizen#190]
# For others languages, there is NOT any bounty!

If you want to translate Arizen to your preferred language please see #173 for details

**Comment by LukasBures** [comment]
#177 partial Polish translation

**Comment by PizzaPete** [comment]
#215 Dutch translation and a fix for the English translation.

**Comment by codygee237** [comment]
Can I help with Cebuano Translation for this project? In ISO 639-2, it is coded as "ceb", hoping for your response. Thank you Sir.

**Comment by woky** [comment]
@codygee237 You definitely can.

**Comment by LukasBures** [comment]
It is not actual no longer, the translations will be needed for v2.0.0.
