### ISSUE TITLE
Arizen wallet address private key

### ISSUE THREAD

**Issue by tsangyeesan** [ZencashOfficial/arizen#191]
I understand the team is going to implement the backup phrase function in the coming updates but is there any way atm to get my private key of my address now?

**Comment by neduchal** [comment]
Hi tsangyeesan,
the only way to get private key is using backup of unencrypted wallet. You can open backup .uawd file in text editor and there you will see all keys.

**Comment by LukasBures** [comment]
has been implemented in #199 - will be in release v1.1.2
