### ISSUE TITLE
Arizen Address Gone From Arizen Wallet

### ISSUE THREAD

**Issue by lojctapc** [ZencashOfficial/arizen#195]
I installed Arizen v 1.1.1 wallet and transferred my ZenCash there. About one week ago, my WIN 10  system rebooted and now after login, my address is not showing, nor are my coins. My address exists still when I go here: https://explorer.zensystem.io/address/

I have an encrypted file backup of the wallet, but that does not seem to import either (.awd) Please help me figure out how to recover my coins. Thank you.

**Comment by edorsey** [comment]
This also occurred for me. Windows 10, after reboot address is no longer there. 

I've since rebooted multiple times and the new address I created after this occurred is still there.

I doubled checked the hash for the installer I downloaded and it matched, also v1.1.1.

**Comment by jaco** [comment]
I have the same issue - my (added manually) address just gone.

Arizen 1.1.1
Mac OS X 10.12.6

**Comment by lojctapc** [comment]
Opened wallet this morning at 9:30 a.m. PST and the address and coins are there now.

**Comment by LukasBures** [comment]
Hello,

there could be 2 issues which I have in my mind:

1) when you manually create walet, it is shown in List of Addresses, then you can copy and use it. When you log in second time, that address "disappear" (but it is still there) but it is hidden in "zero balances addresses" - **that is not a bug that is a feature** 👍 

2) when you send ZEN with fee 0, it can take longer up to few days - blocks have started to be more filled.

L

**Comment by lojctapc** [comment]
Thank you L and thank you to your team as well.

**Comment by jaco** [comment]
1. I have “show zero balances” checked
2. I received my tokens, I saw them in Arizen few minutes after transaction and I see them now in online explorer.

My address just disappeared. I’m afraid that private key is lost too.
