### ISSUE TITLE
Prune wallet backups

### ISSUE THREAD

**Issue by woky** [ZencashOfficial/arizen#212]
Wallet is now saved on every wallet modification plus a backup is made (#211). We should prune old backups in some clever way. I.e. we don't want to keep just last N backups (e.g. user creates N+1 wallets and then the Arizen crashes).

**Comment by LukasBures** [comment]
I would suggest storing only:
- the latest backup from a day
- only last N days, e.g. N=14 days

**Comment by woky** [comment]
Implemented in #274
