### ISSUE TITLE
Remove http from apiUrls

### ISSUE THREAD

**Issue by PersonaOnTheRun** [ZencashOfficial/arizen#213]
I noticed there is an http url in the main.js file within the app folder line 43. Can we either drop this line or switch to https? I realize its probably not a security risk, but I using https is best practice. From what i can tell, it looks like there are two apiUrls in case one fails it switches over to the other. My concern is I believe the default is the http.

> const defaultSettings = {
>     notifications: 1,
>     explorerUrl: "https://explorer.zensystem.io",
>     apiUrls: [
>         **"http://explorer.zenmine.pro/insight-api-zen",**
>         "https://explorer.zensystem.io/insight-api-zen"
>     ],
>     txHistory: 50
> };

**Comment by LukasBures** [comment]
Thank you:

- it will be changed in next release, please see:
https://github.com/ZencashOfficial/arizen/blob/development/app/main.js#L51

- user can add and change the URL position in settings manually

**Comment by PersonaOnTheRun** [comment]
Fastest turnaround I've ever seen. Thank you!

**Comment by LukasBures** [comment]
That change is there longer. But it will be in next release (around 14th January) v1.1.2.
