### ISSUE TITLE
Fix toolbar grid layout

### ISSUE THREAD

**Issue by woky** [ZencashOfficial/arizen#216]
When you shrink the window the Arizen logo keeps too much space which results in left and right buttons wrapping. Grid layout template should keep the logo in the center, but allow side buttons to take the empty space.

Current layout:
```
header {
    grid-area: header;
    display: grid;
    grid-template-columns: 1fr 1fr 1fr;
    align-items: center;
}
```

**Comment by EcutDavid** [comment]
Hey, just sent a PR for fixing this: https://github.com/ZencashOfficial/arizen/pull/255
Please take a look :)

**Comment by LukasBures** [comment]
already fixed
