### ISSUE TITLE
Can't import arizen wallet to Android Wallet

### ISSUE THREAD

**Issue by zay7sev** [ZencashOfficial/arizen#244]
Hello.
Recently I've tried to import my arizen wallet to an Android App so I can bring it with my phone, but it seems that the arizen wallet is backing up the wallet in different file format?
So how i'm supposed to use it at other places?

**Comment by LukasBures** [comment]
Sorry we support only desktop OS: Windows, MacOS, and Linux

**Comment by zay7sev** [comment]
Thanks!
