### ISSUE TITLE
Webroot prevents installation

### ISSUE THREAD

**Issue by rpaulw3** [ZencashOfficial/arizen#245]
After weeks of trying, the Arizen wallet will not install on either Win 8.1 or 10.
Webroot antivirus detects and removes "malware" upon installation.
Update did not fix this.  I really would like to move my Zen from the exchange.
Please advise.

**Comment by nathanhannig** [comment]
My Win 10 wanted to stop the EXE 

I attempted to bypass and then my AVG said the file was infected with Win32:Evo-gen [Susp] virus

**Comment by nathanhannig** [comment]
i ran the file again and it worked, it must have needed to update its database or something :)

**Comment by rpaulw3** [comment]
Still not fixed.  Webroot identifies malware, "W32.malware.gen." and removes two files, leaving wallet not functional.  It is not clear for install on my Win 10 laptop.

**Comment by LukasBures** [comment]
Try to install v1.1.2 if that doesn't work for you, then we cant help you.
