### ISSUE TITLE
Webroot blocks install

### ISSUE THREAD

**Issue by rpaulw3** [ZencashOfficial/arizen#247]
Even thought Zen response is "clear" and "won't fix", the fact remains that as of 11:00 a.m. MST, Jan. 16, 2018, the installation of the Arizen wallet was "blocked" by webroot, "W32.malware.gen", rendering, once again, the wallet no functional. Please advise, as I am losing confidence in this project.
Thanks.

**Comment by LukasBures** [comment]
Ok.
