### ISSUE TITLE
Arizen.Setup.1.1.3.exe 

### ISSUE THREAD

**Issue by Auditman** [ZencashOfficial/arizen#257]
I downloaded the new release 1.1.3 exe to my Win7 and try to install. When I entered the user name, password and repeated the password, I pressed CREATE WALLET, there is no response.
I tried it several times with the same result.
Is the new release window 7 compatible ?
How to solve it ?

**Comment by LukasBures** [comment]
Try running it as Administrator first time.

**Comment by LukasBures** [comment]
And you have to meet all criteria in Password field.

**Comment by Auditman** [comment]
The suggested methods worked. Thanks.
