### ISSUE TITLE
When importing PKs transaction history is not in chronological order

### ISSUE THREAD

**Issue by gsfakianakis** [ZencashOfficial/arizen#260]
See Image:

![image](https://user-images.githubusercontent.com/15521309/35245512-eadabb18-ffc3-11e7-9aa0-44f3e9c36033.png)

**Comment by LukasBures** [comment]
dbbe2527cdf11699a7f0d974c5c405387264c0f8 

this calls multi-refresh transaction history

**Comment by LukasBures** [comment]
Should be fixed in v1.1.8 - #337

**Comment by gsfakianakis** [comment]
In case of new import, txs are added. This is fixed after reloading of the app. Partially fixed in #337. Should stay closed.
