### ISSUE TITLE
Arizen Wallet - shows no addresses

### ISSUE THREAD

**Issue by Crypto-Novice** [ZencashOfficial/arizen#262]
I just downloaded Arizen to my mac for the first time.  It shows no address and when I create a new one I still don't see one.

Also, I was never given a 12, 18, or 24 word recovery phrase to write down.  Seems a bit odd.

Have I downloaded the right wallet?

**Comment by gsfakianakis** [comment]
The download page is:
https://github.com/ZencashOfficial/arizen/releases

Mnemonic phrase is not implemented yet.

After the creation of the account (with username and password) you never saw any zencash address ?

**Comment by woky** [comment]
Use "Show zero balances" checkbox. Reopen the issue if you meant something different.

**Comment by Crypto-Novice** [comment]
Thnx.  I wound up using the swing wallet instead because of the issues with
this one.  Maybe it was me.
