### ISSUE TITLE
Can't login in my Zen arizen wallet

### ISSUE THREAD

**Issue by Dionesjk** [ZencashOfficial/arizen#263]
I can't login anymore . After the new version 1.1.3 appeared. Had logged the last time 19/01 successfully. After 21/01 was login wrong username or passoword appears. I am sure the password and the user are correct. I made several attempts even, including on a different computer and could not. What should I do?

I don't saved the private key. Windows user
print: https://imgur.com/FC1c8lg

**Comment by gsfakianakis** [comment]
See #160

**Comment by woky** [comment]
duplicate
