### ISSUE TITLE
Impossible to execute new withdrawals when an 'UNCONFIRMED' one exist 

### ISSUE THREAD

**Issue by pssm** [ZencashOfficial/arizen#264]
Even when the funds are present, if an withdrawal is pending confirmation (shown as UNCONFIRMED in Transaction History), any subsequently withdrawals will fail with an "Insufficient funds on the source address" error.

<img width="1004" alt="zenbug1" src="https://user-images.githubusercontent.com/125891/35392916-4f7dc89e-01db-11e8-98fc-b13a6002730c.png">

**Comment by LukasBures** [comment]
Thank you, this is common behaving when you have insufficient free UTXOs. This is not a bug this is a feature!

**Comment by pssm** [comment]
Got it, but although the behavior is correct, the message is a poor choice a words, because in fact the funds are there. If it's not possible to make a transfer with UTXOs, display a different error message or lock the button while it's pending confirmation.

**Comment by LukasBures** [comment]
You are right. We will improve it 👍

**Comment by pssm** [comment]
Thanks for the feedback!

**Comment by LukasBures** [comment]
Tex has been updated see 67eca67ecc0d4d40b9f2e924b9f933079833df03
