### ISSUE TITLE
Identified as a threat by Webroot

### ISSUE THREAD

**Issue by keerah** [ZencashOfficial/arizen#267]
![sat](https://user-images.githubusercontent.com/9025818/35489540-e8ec735c-04a8-11e8-8d16-0d9a78714ee2.png)

**Comment by woky** [comment]
Report it to the software/service vendor. I don't know much about Windows malware and I don't know Webroot. Next time, please me bore specific in the issue.

**Comment by LukasBures** [comment]
No reaction.
