### ISSUE TITLE
Attempts to batch withdraw zen from other local addresses to another local address fails with "sendtx_err: Error: socket hang up"

### ISSUE THREAD

**Issue by rterbush** [ZencashOfficial/arizen#268]
Running on Gentoo Linux with Appimage. Very repeatable problem. Version 1.1.3.

**Comment by rterbush** [comment]
Managed to get this to work with 2 source addresses, but >2 fails.

**Comment by woky** [comment]
Try to go to the settings. If you see two URLs in API URLs, try to switch their line order. If you see no URLs, add there this URL http://explorer.zenmine.pro/insight-api-zen.

**Comment by rterbush** [comment]
@woky not sure what that change would do. I am unable to test it at this time as I am attempting to liquidate my arizen wallet. From comments in Discord, @LukasBures appears to know the problem. This problem remains in the latest version.

**Comment by LukasBures** [comment]
Batch-withdraw functionality has been rewritten and will be included in a next release.
