### ISSUE TITLE
Arizen starts and closes.

### ISSUE THREAD

**Issue by DrHighlen** [ZencashOfficial/arizen#271]
Hello, I had updated from one of the older  Orange icon arizen wallets to the  recent realease I can log in fine but when arizen starts  then it closes instantly.

I'm on windows 10 64 bit

**Comment by woky** [comment]
Hi. I've noticed some strange issues on Windows I can't explain. Can you try after log out and log in and even after reboot? I know it sounds crazy.

**Comment by abennu** [comment]
same issue

I'm on macOS 10.12.6

**Comment by LukasBures** [comment]
Try to run it as Administrator for the first time @abennu @DrHighlen  (when your OS is Windows)

**Comment by gsfakianakis** [comment]
@DrHighlen @abennu any update on this ?

**Comment by seet61** [comment]
Linux Mint same issue

**Comment by zennermac** [comment]
Hi there
This issue has been fixed in prior releases, I would encourage you to check out yesterdays maintenance release.
https://github.com/ZencashOfficial/arizen/releases/tag/v1.2.3
