### ISSUE TITLE
Lost Password

### ISSUE THREAD

**Issue by slimmons55** [ZencashOfficial/arizen#282]
This is about a noob screw up as they come.  I downloaded the new arizen wallet and set up the username and password with a password generator app.  I transferred some ZEN over from the Windows swing wallet to the new arizen wallet and did not yet backup my private keys on the arizen and accidentally did not save my complicated password in my password app.  Logged out and can not log back in.
  I have looked in to the password app and can not recover the generated password.
  Have I forever locked my ZEN in my arizen wallet?
Looking for a solution.

Thanks,

**Comment by LukasBures** [comment]
I am sorry to tell that to you, but yes, you have lost all your ZENs. There is no way how to recover it without `uawd` backup or `PKs`.

**Comment by ponta9** [comment]
IF you remeber anything anything about the pass save it and maybe you can brute force it open later
