### ISSUE TITLE
RFE:  User Manual update Swing to Arizen Wallet transfer

### ISSUE THREAD

**Issue by roleerob** [ZencashOfficial/arizen#286]
Good evening,

Having just learned about this wallet (frustrations with ZenCash Swing wallet), I was immediately impressed by seeing a User Manual PDF to download.  Thank you @Tigger!!  Looks like a very nice wallet for us to consider.

Any chance details could be provided for how users can transfer their ZEN from the Swing to the Arizen wallet?  I realize you could presumably simply send and receive, but I was hoping Arizen may have some way to import the user's keys and ZEN directly.

Thanks again!

Respectfully,

Roger

**Comment by LukasBures** [comment]
Hellow @roleerob ,

you have at least 2 options:
1) send your ZENs over blockchain
2) export your PKs from Swing and then import them in Arizen - it is already described in User Manual, see 1.3 section:

<img width="780" alt="snimek obrazovky 2018-02-20 v 7 17 18" src="https://user-images.githubusercontent.com/3979946/36409859-4396b026-160e-11e8-8c06-0b6f1cd59fb2.png">

**Comment by roleerob** [comment]
Hi LukasBures,

Thank you kindly for your prompt response.  I feel bad taking your time, as you have rightly pointed out this topic is already covered!

I will try the export / import of private keys.  I am new to all of this, but hopefully I can navigate through it without any problems.

Thanks again sir!

Respectfully,

Roger
