### ISSUE TITLE
Unable to access wallet

### ISSUE THREAD

**Issue by cmenge20** [ZencashOfficial/arizen#294]
Hi,

I have recently starting mining zencash and have money in a wallet that I made but have been unable to access it.  Is there anyway that I can recover this money.  I have since made a new wallet will be mining to that one. 

Thanks for the help

**Comment by gsfakianakis** [comment]
Please go to the wallet path and see if the wallet that you refer to exists. The wallet name is username.awd

The path to the awd file is:
Linux: ~/.arizen/wallets/wallet_username.awd
Windows: C:\Users\username\AppData\Roaming\Arizen\wallets\wallet_username.awd
Mac: /Users/username/Library/Application Support/Arizen/wallet_username.awd
