### ISSUE TITLE
Move translation dictionaries to *.poperties format

### ISSUE THREAD

**Issue by woky** [ZencashOfficial/arizen#296]
Currently we store translation entries in the JSON as multi-level dictionary. The only advantage this format gives is the ease to parse it (it's JSON). But it's not suitable for anything else. The dictionary should be a single level map. We need to get a value of a key. We never need to get a sub-dictionary of a key.

There's a popular format in Java for translation dictionaries: https://en.wikipedia.org/wiki/.properties. It's simple key-value text file.

In current JSON format
- It's complicated to add new keys. Compare adding `foo.bar.baz` with value of `Hi` into the JSON compared to adding it into properties file.
- it's complicated to lookup a key.
- it's complicated to add an entry programatically without introducing other changes

We should switch to some better format. The properties format fits but we'll have to make or find a parser for JavaScript.

**Comment by zennermac** [comment]
Thi likely will not be implemented now that Sphere By Horizen is available.
