### ISSUE TITLE
Unable to transfer wallet balance from Arizen to other wallet.

### ISSUE THREAD

**Issue by rterbush** [ZencashOfficial/arizen#300]
I've been transferring from individual securenode addresses out to a different wallet. This has progressed without significant issue until I reach the final address. 

Attempts to transfer the remaining balance from this last address result in `sendtxErr: Error: socket hang up` errors.

Running appimage on Gentoo.

**Comment by Slashroot101** [comment]
I am getting the exact same problem.

**Comment by LukasBures** [comment]
Hello, have you tried the batch withdrawal or just send method?

**Comment by rterbush** [comment]
@LukasBures I believe that I eventually worked around this by using batch and telling it to leave 0.0. I thought I had updated this issue with that workaround, but appears I did not.

**Comment by LukasBures** [comment]
Hello @rterbush , has been this issue solved or could you provide a better explanation, please?

**Comment by rterbush** [comment]
@LukasBures sorry, I am not currently running Arizen so I cannot confirm that this is resolved. I would suggest closing. I will open another issue if I discover a problem.

Thanks
