### ISSUE TITLE
Wallet available balance calculator has rounding error

### ISSUE THREAD

**Issue by rterbush** [ZencashOfficial/arizen#301]
I'm attempting to transfer a balance out of Arizen to zero out the wallet address. 

The balance is: 42.12345678
I am attempting to transfer: 42.12335678 to accommodate the 0.00010000 transaction fee.
Arizen is incorrectly telling me there are not sufficient funds.
Changing the amount transferred to 42.12335677 fixes the error.

This seems to have worked fine as I transferred balances from other addresses in the wallet. But now that I am at the final address with a balance, this error appears.

**Comment by rterbush** [comment]
I was able to work around this by doing the transfer in a batch transfer although it took two tries with the first try erroring out with `sendtx` error.

**Comment by LukasBures** [comment]
Should be fixed. Will be included in next release v1.1.6.
