### ISSUE TITLE
Z Transactions using trusted Secure Node(s)

### ISSUE THREAD

**Issue by gsfakianakis** [ZencashOfficial/arizen#302]
Possibility of Z transactions using secure node(s) trusted by the user

Main idea:
- Add FQDN of trusted Secure Node (SN) by the user in settings
- RPC calls to make new Z address (z_getnewaddress)
- RPC calls to send ZEN, get transactions and check balance (sendfrom, gettransaction, z_getbalance "address")

So arizen is an Interface to the trusted securenode sending all zen-cli commands to SN, where commands are executed.

**Attention: The PKs will be stored in the Secure Node**

Features in bullets:

- User inputs FQDN of SN in settings
- User inputs username of SN in settings
- User can select save or not password of SN in settings
- Import in Arizen existing z addresses (if user wants to)
- Make new Z address
- Receive transaction
- Update Balance
- Send ZEN from Z address

**Comment by LukasBures** [comment]
Has been merged and will be included in #322
