### ISSUE TITLE
feature request - better coin control and transaction visibility

### ISSUE THREAD

**Issue by nikmit** [ZencashOfficial/arizen#305]
@cryptolawjunkie on telegram suggested that having better visibility of the available transactions within an address would be really good. Particularly when making payments from a wallet which contains stake addresses - would be nice to know in advance which transactions will be used and what will remain in the source address afterwards. Seems like a very good idea.

**Comment by LukasBures** [comment]
@nikmit thank you for the suggestion, but could you describe it a little bit more?

For sending funds from staking addresses has Arizen "Batch Withdrawal" method - which allows you send all funds over a selected threshold (e.g. 42 ZEN).

**Comment by nikmit** [comment]
Sorry for the late response - must have missed the response notification. Yes - the "Batch Withdrawal" method should do it. Should have checked what's available myself before submitting this here :)
