### ISSUE TITLE
Crashing at login

### ISSUE THREAD

**Issue by garypalmerjr** [ZencashOfficial/arizen#313]
Then login screen appeared, after I enter my data the wallet just crashes. No errors or nothing. Gone. (If I enter wrong data it tells me it is wrong, the correct details crash the wallet.) Please advise. Ty.

**Comment by LukasBures** [comment]
Hello,

If you runs it on Windows, try to runs it with Administrator right for the first time.

Lukas


Odesláno z iPhonu

24. 4. 2018 v 17:20, Gary Palmer Jr. <notifications@github.com>:

**Comment by garypalmerjr** [comment]
I tried -- It still shut down. (I also had restarted the comp.)

**Comment by slashdots** [comment]
I am experiencing the same issue on Windows 10. Crashes immediately upon login. No error message.

**Comment by garypalmerjr** [comment]
I am still having this issue. Please assist.

**Comment by gsfakianakis** [comment]
Could you please make a new wallet and login to the new wallet ?

**Comment by gsfakianakis** [comment]
Closed for inactivity. Please comment again to open if problem insists.
