### ISSUE TITLE
Attempted sending of unshielded coinbase UTXO

### ISSUE THREAD

**Issue by tarrenj** [ZencashOfficial/arizen#318]
Arizen does not check if a UTXO is from a coinbase TX before attempting to spend it. The UTXOs seem to be picked in a FILO fashion, so users who receive coinbase UTXOs to an address within Arizen will be unable to spend any UTXOs.

This could be done similarly to the confirmation count check [here](https://github.com/ZencashOfficial/arizen/blob/master/app/main.js#L1303-L1305).

**Comment by tarrenj** [comment]
Additionally, Arizen fails to display the correct balance if an address receives a UTXO from a coinbase TX.

**Comment by LukasBures** [comment]
Like this line: https://github.com/ZencashOfficial/arizen/blob/master/app/main.js#L1335

**Comment by LukasBures** [comment]
Script for testing, if in YOURADDR are coinbase ZENs. It needs a shell, curl and jq:

`addr=YOURADDR
curl -s http://explorer.zenmine.pro/insight-api-zen/addr/$addr/utxo | jq -r '.[].txid' | while read tx; do
        curl -s http://explorer.zenmine.pro/insight-api-zen/tx/$tx | jq .isCoinBase
done`

Thank you @woky

**Comment by LukasBures** [comment]
Fixed in: 2aeb9f238fa8cd7d5af8ffaad4de3d2b94fbd00c
Will be included in v1.1.7
