### ISSUE TITLE
Where are wallet files stored on macOS?

### ISSUE THREAD

**Issue by tsujp** [ZencashOfficial/arizen#320]
All good having a backup option in the menu system, but where is the wallet file actually stored on mac in case we say forgot our password and wanted to backup manually but can't because we cannot login.

**Comment by Tigger1** [comment]
Hi @tsujp ,

thanks for using GitHub. The answer for your question is in Arizen Manual - I made a screenshot for you:
<img width="589" alt="snimek obrazovky 2018-05-14 v 14 48 04" src="https://user-images.githubusercontent.com/32774850/39998337-0de4bf18-5786-11e8-8cd6-d1798a20c48b.png">

Please let me know if it was helpful or not.
Best regards,
Kamila (@Tigger1)

**Comment by LukasBures** [comment]
No response closed.
