### ISSUE TITLE
Sort & view transactions by wallet address

### ISSUE THREAD

**Issue by avataraustin** [ZencashOfficial/arizen#329]
Have the Arizen wallet sort & view transactions by wallet address.

Why?: Right now for example, if a person is receiving many payments to multiple addresses (mining or node hosting for example) there is no easy way to see which address received the payment. Whereas if we could click on a wallet address and then see transactions just for that address it would greatly improve the user experience.

**Comment by LukasBures** [comment]
Thank you for your feature request, I think it is the good point. We will consider it and probably include in one of next versions.

Lukas

**Comment by zennermac** [comment]
This likely won't be fixed as a priority for Arizen as we have similar functionality now available in Sphere By Horizen
