### ISSUE TITLE
Ability to export transaction history to CSV, or copy-paste cleanly from Transaction History

### ISSUE THREAD

**Issue by alextilson** [ZencashOfficial/arizen#331]
This is a common feature of other desktop wallets, and an essential feature for users who need to track mining income or transactions in 3rd party tools.

Currently, copy-pasting from the Transaction History panel results in a single column in Excel, with dates in a format that Excel cannot understand. So, even a MVP work-around does not currently work well.

**Comment by cryptostevo** [comment]
I second this. Would be extremely helpful in tracking mining income for tax purposes (to then import csv file into cointracking or bitcoin tax, etc.

**Comment by cryptostevo** [comment]
Hi @LukasBures, do you have plans to add this to a future version? 
Some of the key data that bitcoin.tax for example needs from a CSV is below (copied from their website). Several other coin tracking (for tax purposes) sites use the same or similar info. I have put in requests at multiple sites (bitcoin.tax, tokentax, etc) to create an API that scans the blockchain explorer and automatically records the transactions. No luck yet. 


Select one or more comma-separated files from your computer. The files must either contains the following fields or have these names in the header row:

Date (date and time as YYYY-MM-DD HH:mm:ss Z)
Action (INCOME, GIFT or MINING)
Memo (optional, name of sender or item sold)
Source (optional, source or wallet name, e.g. Coinbase or Blockchain)
Symbol (BTC, ETH, LTC, etc)
Volume (number of coins received)
Total (Fair price or value in Currency or your home currency, or blank for market value
Currency (optional, specify an alternative to your default currency, such as USD, GBP or EUR)

For example: 
Date,Action,Source,Symbol,Volume
2014-01-01 13:00:00 -0800,INCOME,"Blockchain Wallet",BTC,1

**Comment by zennermac** [comment]
I would suggest adding this as a feature request to Sphere By Horizen, Arizen will likely only be updated by exception going forward.
https://github.com/ZencashOfficial/Sphere_by_Horizen
