### ISSUE TITLE
Long rpcpassword causes incorrect password attempt

### ISSUE THREAD

**Issue by koljenovic** [ZencashOfficial/arizen#332]
When using a 128 character long alphanumeric rpcpassword Arizen 1.1.7 fails to establish RPC connection with the secure node, most probably the password gets trimmed somewhere. The secure node reports the following error:

`2018-05-31 21:59:43 ThreadRPCServer incorrect password attempt from 127.0.0.1:49016`

After shortening the password to 64 characters the connection gets established successfully and the Z addresses sync.

P.S. ~~After some further monitoring I can report that the same error keeps reoccurring on some calls.~~ The reoccurring attempts were from the securenodetracker as I forgot to run the setup again for the configuration changes to change effect.

**Comment by gsfakianakis** [comment]
Most probably is limit of RPC server. I will check it.

**Comment by gsfakianakis** [comment]
I tried with long password (128 chars) and it works fine, both locally and from Arizen using RPC.
If you tried again and did not work with 128 chars, then use 64.
