### ISSUE TITLE
GPG key for SSH authentication

### ISSUE THREAD

**Issue by satoshi-ninja** [ZencashOfficial/arizen#334]
For the secure node configuration in the settings, it would be great if you could implement gpg key auth into SSH, next to the user/password SSH authentication method already available.

**Comment by ThomasFreedman** [comment]
Not sure about GPG, may be the same thing as I use but referred to by different name.

I would like to see public/private key pair authentication for sec nodes. This is important, as password auth is a far weaker authentication mechanism. I will not enable password authentication on my nodes, but I would very much like to utilize the enhanced security / privacy features of the newest Arizen wallet.

**Comment by satoshi-ninja** [comment]
@ThomasFreedman I mean the same as you mean :)

**Comment by joWeiss** [comment]
I actually enabled SSH login with username/password out of curiosity just for Arizen.

But I support @ThomasFreedman and @satoshi-ninja and would really like to see a _Login with SSH key/Certificate_ option.

**Comment by LukasBures** [comment]
Will be included in v1.1.9
