### ISSUE TITLE
Can't log in to Arizen v1.1.8

### ISSUE THREAD

**Issue by milyway** [ZencashOfficial/arizen#340]
Hi,

I have Arizen v1.1.8 on windows 7,

Yesterday everything worked fine., But today I can't log in .
It keeps saying that I have wrong wallet name or password, which is not that case.
I've tried to download again form Github and reinstall, did not work.
and I've tried to do other methods written on [#160](https://github.com/ZencashOfficial/arizen/issues/160) but can't find wallet_username.awd, may be it's different for v1.1.8 ?

I'd greatly appreciate your help.
Thank you.

**Comment by gsfakianakis** [comment]
The wallet_username.awd shoule be in the same place as mentioned in the #160 .

If wallet_username.awd is not there, please put one of your backups.

**Comment by LukasBures** [comment]
Duplicate: use #160
