### ISSUE TITLE
Paper wallet PDF export doesn't work

### ISSUE THREAD

**Issue by tahv0** [ZencashOfficial/arizen#349]
No new pdf pops up and no new pdf can be found from fs after operation.

Tried on:
- Arizen 1.1.8
- Windows 10

**Comment by tahv0** [comment]
Possible fixed here?
https://github.com/ZencashOfficial/arizen/pull/348/commits/8169db886e3ee9ac7e940f519874506ec9f443f4

**Comment by gsfakianakis** [comment]
Yes. Will be included in v1.1.9
