### ISSUE TITLE
Arizen Wallet Stuck on Certain Date

### ISSUE THREAD

**Issue by cryptostevo** [ZencashOfficial/arizen#353]
My Arizen wallet hasn't received a transaction since July 5th at 1:01PM. It's my mining income wallet, so it receives zen every 30minutes or so. I did an encrypted backup of the wallet. Closed and re-launched. Restarted the wallet, restarted the computer, and then the wallet. Tried several ISPs and connections to see if there was something blocking in. Loaded the wallet on another computer and still the same issue. The loading icon in the bottom right is always spinning. The block explorer correctly shows my mining income, but its just not arriving into the wallet. Any thoughts on how to fix this? Thank you!

<img width="904" alt="screenshot 2018-08-02 14 07 27" src="https://user-images.githubusercontent.com/42045554/43611275-67d72d10-965d-11e8-85d7-a67cbdf70d0c.png">

This is on macOS. Both computers are macOS. 
Wallet v1.1.8

**Comment by cryptostevo** [comment]
Update in case anyone else has the same issue. Tried a bunch of stuff, but since I had the encrypted backup and that would at least load (although it would be stuck), I then exported private keys, deleted Arizen, re-installed Arizen, created a new wallet and then imported the private keys. Loaded up fine, transactions and blockchain are now syncing fine. Still not sure why the glitch happened though.

**Comment by Joykiller** [comment]
Yep also getting same issue i tried your method but still failing.

It's actually caused by an API Failure.

**Comment by LukasBures** [comment]
Check your API addresses - if you are able to reach them. Disable domain fronting in your settings. Upgrade to v1.1.9 (it should be faster than v1.1.8). And I hope it will help you.

**Comment by Joykiller** [comment]
Domain fronting is disabled, still getting API issues due to timeouts often, however refreshing or restarting some times makes it work. Maybe a thread issue?

**Comment by LukasBures** [comment]
Try to change the order of APIs ...

**Comment by Joykiller** [comment]
Yep, I've done that also removed some.

**Comment by cryptostevo** [comment]
Just an update. I used private key to install on a separate computer, it loaded up and synced fine. Ran a backup, then deleted the arizen wallet from the main computer and then installed the v1.1.9 and loaded up the new backup. It loaded up and syncs fine now.

**Comment by gsfakianakis** [comment]
Thanks for the update.

**Comment by kbs1** [comment]
Still getting tihs issue. I can't even create a new wallet without getting timeouts from explorer API or socket hangups in the console. The spinner at bottom never stops spinning. Reaching the urls from a web browser on the same machine works great though.

**Comment by gsfakianakis** [comment]
New update is coming that will fix it. 
Restart you Arizen and check your internet connection.

**Comment by kbs1** [comment]
Still the same problem, with deleted $HOME/.arizen folder and creating a new wallet, initial refresh fails with socket hangups or timeouts :( network on the machine is working great. Also, why does arizen create so many addresses in the new wallet? I hope the fix is incoming soon.
