### ISSUE TITLE
Unable to generate new T address

### ISSUE THREAD

**Issue by MSauce** [ZencashOfficial/arizen#355]
**Describe the bug**
Unable to create new T address using 1.1.9 with brand new wallet. 

**To Reproduce**
1. Install wallet
2. Click on "Get a new address"
3. Hit Create
4. Nothing happens, create a new address window stays present

**Expected behavior**
A new T address should be generated.

**Please complete the following information:**
 - OS: Getting same result with both Windows and OSX on separate wallets
 - Version 1.1.9

**Comment by gsfakianakis** [comment]
Thanks @MSauce 
Fixed in #356

**Comment by gsfakianakis** [comment]
If you have and configure a remote node for Z addresses then it works.

**Comment by LukasBures** [comment]
@MSauce thank you, fix will be included in next release v1.2.0 - which will be released this month.

**Comment by LukasBures** [comment]
Will be included in #358 see: c8a84184bbc151af245b6583136c681fa42a1223
