### ISSUE TITLE
Max button in the "Withdraw" tab not always working

### ISSUE THREAD

**Issue by omega32** [ZencashOfficial/arizen#357]
Max button in the "Withdraw" tab not working when selecting the address directly from the "Overview" tab.

1. Open and login to your Arizen wallet.
2. On the "Overview" tab, find an address with some zen (e.g.: 1 ZEN).
3. Click on the red up arrow ("Withdraw from this address"). The "Withdraw" tab will then open.
4. Click the "Max" button. The "amount" of the "Withdraw" will not be set; it stays at zero.

**Expected behavior**
The amount should be set to the total balance of the selected address, minus the fee (e.g. 0.9999 ZEN).

 - Version 1.1.9

**Comment by LukasBures** [comment]
Thank you, we will fix it.

**Comment by LukasBures** [comment]
Will be included in #358 - see: c0f19f353138532b7b0a6ee450498282f2312796
