### ISSUE TITLE
Custom API URL not working

### ISSUE THREAD

**Issue by romali** [ZencashOfficial/arizen#359]
Arizen is not sync with information from exporer. After changed api servers, arizen still choose 'explorer.zensystem.io' as default, please check attachments.
 - OS: Linux
 - Version  <1.91 AppImage
 - Domain fronting disabled

**Arizen Settings:**
![arizen_api](https://user-images.githubusercontent.com/5367174/44085201-0eca6bfa-9fb9-11e8-968d-37c40dda3558.png)

**Output from console:**
![arizen_api_url](https://user-images.githubusercontent.com/5367174/44085202-0eede6b6-9fb9-11e8-8898-9163235cb53a.png)

**Comment by gsfakianakis** [comment]
Can you replace the following urls in your API URLs in settings and try again ?

https://explorer.zensystem.io/insight-api-zen
https://explorer.zen-solutions.io/api
http://explorer.zenmine.pro/insight-api-zen

**Comment by romali** [comment]
Currently don't have new transaction, I can't determine if the wallet has updated the data from the explorer, but axios module still returned followings errors:

![ari](https://user-images.githubusercontent.com/5367174/44257458-60138780-a20c-11e8-8113-3198db5d4dba.png)

![ari1191](https://user-images.githubusercontent.com/5367174/44257460-60138780-a20c-11e8-8782-0b9d22a89951.png)

**Comment by gsfakianakis** [comment]
If you make a new wallet, do you get this error ?

**Comment by romali** [comment]
Yes, `timeout `or `socket hang out` error. For the test I created new wallet on two different Ubuntu version.

**Comment by romali** [comment]
Arizen on Centos show the same errors.

**Comment by kbs1** [comment]
Same problem here, creating a new wallet doesn't work, newest AppImage 1.2.0

**Comment by kbs1** [comment]
API URLs are also ignored

**Comment by zennermac** [comment]
I would suggest trying yesterdays maintenance release.
All of these issues have been addressed.
https://github.com/ZencashOfficial/arizen/releases/tag/v1.2.3
