### ISSUE TITLE
Max doesn't send Max

### ISSUE THREAD

**Issue by DatDraggy** [ZencashOfficial/arizen#360]
**Describe the bug**
When the fee is modified and you click the Max button, the fee is reset to 0.0001 and max only changes to maxamount - 0.0001
It should work with the custom fee

**To Reproduce**
1. Click Withdraw
2. Choose the addresses
3. Modify fee
4. Click max

**Expected behavior**
Leave fee and calculate max correctly

**Please complete the following information:**
 - OS: macOS 10.13.6
 - 1.1.91

**Comment by gsfakianakis** [comment]
@DatDraggy You are right. Will be fixed soon and be included in v1.2.0

**Comment by gsfakianakis** [comment]
Fixed in #361
