### ISSUE TITLE
Error when importing encrypted keys

### ISSUE THREAD

**Issue by joao-roberto** [ZencashOfficial/arizen#363]
**Describe the bug**
I've created my wallet with that version that couldn't create a T-addr, i had to format my pc so i've copied a encrypted version(im freaking out) of my wallet (.awd i guess), i've formatted my pc (win 7 to win 10) and now i cant import my wallet, isn't wrong pass or user.

**To Reproduce**
Method 1:
1-create a new wallet
2-import encrypted .awd
3-show if i want to replace the wallet
4-click yes
5- it was supposed to ask for my encryption key, right ? but...
6-nothing happens

method 2:
1-go on menu before login
2-browse the walled .awd
3-put the login and password (even with a fake password enters normally)
4-press enter
5-enter the wallet, but not my wallet
6- nothing happens
**Expected behavior**
To import my keys but none of the ways shows nothing 

 - OS: created wallet on old arizen (that version where you couldn't create a T-addr) on my win7, error on my win 10 with the newest version 1.2.0 (i guess)

**Additional context**
Please, say that it is a bug, im freaking out. Thank you for your kindness, friends.

**Comment by gsfakianakis** [comment]
Go to the wallet folder and copy your backup file. 
Rename your backup file to username.awd and open Arizen
Login with your username and password

The path to the wallet folder is:
Linux: ~/.arizen/wallets/
Windows: C:\Users\username\AppData\Roaming\Arizen\wallets\
Mac: /Users/username/Library/Application Support/Arizen/

**Comment by joao-roberto** [comment]
I`ve tried your way @gsfakianakis but when i click(or enter) doesn`t show anything(tried with wrong password and doesn`t say it`s a wrong password either) and i keep clicking enter or mouse click on login, seems like nothing is happening.

**Comment by joao-roberto** [comment]
Thanks guys, it's working 
1) Take your right backup and put in on a desktop.
2) Move all of your backups from "C:\Users\username\AppData\Roaming\Arizen\wallets" and put them on a different place.
3) Open Arizen click "Create wallet", use wallet name and password you used to use before (warning: it's case sensitive). The backup file has to have the same name as the wallet name you're gonna to type in.
4) Choose your backup file from the desktop and click on "Create wallet".
5) Log in with your correct credentials.

**Comment by Tigger1** [comment]
This issue was solved with suggested steps above ^^^ by Arizen Team on ZenHelp. The Ticket on ZenHelp will be closed.

**Comment by joao-roberto** [comment]
Yes, thanks a lot, Spencer and Kamila.
