### ISSUE TITLE
typo on source url during autoupload from version 1.1.91 to 1.2

### ISSUE THREAD

**Issue by romali** [ZencashOfficial/arizen#365]
**Describe the bug**
Auto upload is pointing to file x96_64 instead x86_64, and also gives a wrong status "New version 1.2.0 has been downloaded" which is not true because file Arizen-1.2.0-x96_64.AppImage not exists.

```
./Arizen-1.1.91-x86_64.AppImage 
Found version 1.2.0 at https://github.com/ZencashOfficial/arizen/releases/download/v1.2.0/Arizen-1.2.0-x96_64.AppImage
Downloading updates from https://github.com/ZencashOfficial/arizen/releases/download/v1.2.0/Arizen-1.2.0-x96_64.AppImage
New version 1.2.0 has been downloaded
```
 - OS: Linux Ubuntu
 - Version 1.1.91 Apimage

**Comment by LukasBures** [comment]
Thank you!

Fixed: 678b4011637a8eaec24618cf71f642ebf7014e57
