### ISSUE TITLE
Arizen log in error, nothing happens

### ISSUE THREAD

**Issue by BigMank** [ZencashOfficial/arizen#368]
Hello,
I am using Arizen version 1.1.7 and I cannot log in. Back in January I had a log a similar log in error and luckily gsfakianakis was able to guide me through it (hoping you can help me again gsfakianakis).
I tried to log in with my correct user and password and literally nothing happens. No error message, nothing. It just allows me to press the log in button and absolutely nothing.  Should I upgrade to the latest version. I truely am starting to hate Arizen Wallet and I want to switch to another wallet, assuming I can get my Horizen from the Arizen wallet first. Thank you very much.

**Comment by gsfakianakis** [comment]
Hi @BigMank, 

Please download the latest version from here:
https://github.com/ZencashOfficial/arizen/releases

Unistall the previous version and install the new.
Then tr again and let us know what happens.

**Comment by BigMank** [comment]
So upon rechecking I am already using version 1.2. 
I did not un-install it yet. SHould I un-install and try to log in again?

**Comment by gsfakianakis** [comment]
Yes please.

**Comment by javajox** [comment]
I have the same problem in Ubuntu 18.04.1. The wallet is not working, it always gave me errors like "socket hang up". Seems like API servers are unresponsive.

**Comment by gsfakianakis** [comment]
Hi @javajox ,

We are fixing this problem and it will be included in the next arizen release. You can move your wallet in a windows PC or a mac. There it works fine.

**Comment by gsfakianakis** [comment]
Just try to install Arizen agaiin, without uninstall. It will be uninstalled (if not yet).

**Comment by jonas3210** [comment]
Hi, i have the same issue. Using arizen wallet version 1.2.0 on Windows 10 and have already uninstalled and reinstalled the wallet again. If i try to log in nothing happens. If I type a wrong username it shows wrong username but if i type the right or a wrong password nothing happens. Is there any solution despite reinstalling the wallet?

**Comment by zennermac** [comment]
I would encourage you to try yesterdays maintenance release
https://github.com/ZencashOfficial/arizen/releases/tag/v1.2.3

If you still see the same issue, this is likely related to missing special characters from your password.
If this is the case please open a ticket on the 24/7 support desk and we can give you some more interactive support. https://support.horizen.global
