### ISSUE TITLE
I can no longer connect to my secure node via RPC

### ISSUE THREAD

**Issue by ebadiere** [ZencashOfficial/arizen#370]
**Describe the bug**

I have been able to connect to my secure node in the past and take advantage of the sending to a z_ address feature in arizen.  For some reason I can no longer connect via RPC and therefore I am not able to send transactions to z_ addresses.  I reviewed my secure node port, username and password in the zen.conf file and they are correct. The right dot at the bottom is red while the left dot is green.  Is there a log file or console I can look at for a detailed description of the connection issue?

**To Reproduce**
1. Logged into my wallet.
2. Click on 'settings' to ensure all was correct.
3. Tried to withdraw a small amount of zen from a t_address and send to my z_address
4. No error, just sits there and does nothing with the right dot red.

**Expected behavior**
My zen amount to be sent to my z_address

**Screenshots**

**Please complete the following information:**
 - OS: MacOS
 - Version 1.2.0

Let me know if you need more information.

**Comment by gsfakianakis** [comment]
Hi @ebadiere ,

Please log in to your node via ssh and check that everything works fine via ssh.

If yes, please type the following commands in your ssh terminal:
1) sudo apt install curl
2) curl --user myusername --data-binary '{"jsonrpc": "1.0", "id":"curltest", "method": "getinfo", "params": [] }' -H 'content-type: text/plain;' http://127.0.0.1:8232/

myusername = is your username and find also your password as it will be required.

check both in ~/.zen/zen.conf

Let us know if you have any question.

**Comment by ebadiere** [comment]
I got:

curl: (7) Failed to connect to 127.0.0.1 port 8232: Connection refused

Since the rpcport in my zen.conf is set to 8231, I tried that as well and still got:

curl: (7) Failed to connect to 127.0.0.1 port 8231: Connection refused

**Comment by gsfakianakis** [comment]
1) Then go to ~/.zen/zen.conf and check the following settings are like the following:

rpcallowip=127.0.0.1
server=1
daemon=1
listen=1
txindex=1
logtimestamps=1

If not modify and save.

2) Then please type the command:
zen-cli help getinfo

and see the last line, should be like this ...  curl --user myusername ....

Copy paste this and replace with your username and then put your password when requested.

Make sure you have correct username and password as it seems that they are not correct. Maybe it is an extra space before or after your username/password.

**Comment by ebadiere** [comment]
Is there anything else I can check?

**Comment by gsfakianakis** [comment]
It seems that RPC is not working properly. Do you have another secure node to try to connect?

**Comment by ebadiere** [comment]
Okay yes, I tried the same thing on another one of my nodes.  Same result.  I followed the setup instructions to set up my secure nodes.  I copy/pasted most if not all of the commands.  In this process I am somehow not setting up or enabling RPC.

**Comment by ebadiere** [comment]
Okay  so my port number was wrong up to now.  Sorry.  When I use the port number from the config file, that is 18231, I get the following:
Enter host password for user 'q1Rt7xjWiuBMGASMoY18fxhGjBdjaE3w':
{"result":{"version":2001550,"protocolversion":170002,"walletversion":60000,"balance":0.00393721,"blocks":397965,"timeoffset":0,"connections":25,"proxy":"","difficulty":3300764.860064694,"testnet":false,"keypoololdest":1534082098,"keypoolsize":101,"paytxfee":0.00000000,"relayfee":0.00000100,"errors":""},"error":null,"id":"curltest"}

**Comment by ebadiere** [comment]
I updated my wallet settings, that is just the port number and I am still seeing the red dot.

**Comment by gsfakianakis** [comment]
Please check that the ssh settings are correct and that you can login with the credentials in your settings. 
Did you change your password lately ?

**Comment by ebadiere** [comment]
I did not change my password lately.  My ssh login and password are correct.  The left dot in the wallet is green.  I was logging into my secure node as part of the debugging process above.

**Comment by gsfakianakis** [comment]
Everything seems normal.
Did you try to change your arizen settings to your 2nd node and connect ?

**Comment by ebadiere** [comment]
I tried updating the rpcallowip setting to my client machine and it still did not work, so I set it back.  How does this work?  It connects via ssh and then what?

**Comment by ebadiere** [comment]
So the problem is with my vps provider.  When I tested it with one of my nodes from another provider I was able to connect.  Some service is not enabled.

**Comment by gsfakianakis** [comment]
Ok. Then most probably the rpc port is blocked. Ask them to open this port for you or maybe you can do it in the firewall of your VPS.

I will close the issue as it is related to VPS provider. Comment again if you need any more help.
