### ISSUE TITLE
Segementation fault on Kubuntu 18.10

### ISSUE THREAD

**Issue by Alwinius** [ZencashOfficial/arizen#371]
**Describe the bug**
I cannot run the latest release of the Arizen wallet as AppImage or installed via dpkg on my Kubuntu 18.10. I could run 1.1.3 on Kubuntu 18.04, after I updated my OS, it did not work any more, the error was 
`./Arizen-1.1.3-x86_64.AppImage: 2: ./Arizen-1.1.3-x86_64.AppImage: Syntax error: newline unexpected`
Then I downloaded the new version 1.2 and the error is
`[1]    15368 segmentation fault (core dumped)  ./Arizen-1.2.0-x86_64.AppImage`
Then I installed 1.2 from the .deb, but the error is the same
`[1]    15521 segmentation fault (core dumped)  /opt/Arizen/arizen`

Please tell me if I can help fixing the bug

**Comment by zennermac** [comment]
I would encourage you to try yesterdays maintenance release.
This has been tested across all platforms and is confirmed working.
https://github.com/ZencashOfficial/arizen/releases/tag/v1.2.3
