### ISSUE TITLE
Wallet is stuck on a certain date

### ISSUE THREAD

**Issue by pmensik** [ZencashOfficial/arizen#390]
I know there is an already closed bug for this but none of the solutions really worked for me. I am running some secure nodes and wallet is used for receiving the payments (payments were received roughly once a week and then it stopped at the end of the September).  
I checked that domain fronting is disabled. 
This is a list of APIs URLs
```
http://explorer.zenmine.pro/insight-api-zen
https://explorer.zensystem.io/api
https://explorer.zensystem.io/insight-api-zen
https://explorer.zen-solutions.io/api
```
I tried to switch the order but it didn't help. 
I've also tried to update to the newest version of Arizen but that didn't help either. I run the Arizen via AppImage file.
So now I feel I kind of ran out of options except installing Arizen to another computer (which is not desirable for me). Or is there a way how to switch with my account to the new Sphere wallet?
I also enclose the exception from the log
```
Update from API failed { Error: timeout of 30000ms exceeded
    at createError (/tmp/.mount_ArizenXy0ZS4/app/resources/app.asar/node_modules/axios/lib/core/createError.js:16:15)
    at Timeout.handleRequestTimeout [as _onTimeout] (/tmp/.mount_ArizenXy0ZS4/app/resources/app.asar/node_modules/axios/lib/adapters/http.js:216:16)
    at ontimeout (timers.js:475:11)
    at tryOnTimeout (timers.js:310:5)
    at Timer.listOnTimeout (timers.js:270:5)
  config: 
   { adapter: [Function: httpAdapter],
     transformRequest: { '0': [Function: transformRequest] },
     transformResponse: { '0': [Function: transformResponse] },
     timeout: 30000,
     xsrfCookieName: 'XSRF-TOKEN',
     xsrfHeaderName: 'X-XSRF-TOKEN',
     maxContentLength: -1,
     validateStatus: [Function: validateStatus],
     headers: 
      { Accept: 'application/json, text/plain, */*',
        'User-Agent': 'axios/0.18.0' },
     method: 'get',
     baseURL: 'https://explorer.zensystem.io/insight-api-zen',
     url: 'https://explorer.zensystem.io/insight-api-zen/addr/znXzLaJVeiXNFTcxMFvz3BtBjhn4PoRj9sq',
     data: undefined },
  code: 'ECONNABORTED',
```

**Comment by zennermac** [comment]
Hi there

I encourage you to install the very latest release of Arizen as there have very recently been a number of performance improvements and also transaction processing updates.

https://github.com/ZencashOfficial/arizen/releases/tag/v1.2.3

**Comment by zennermac** [comment]
All issues mentioned above are confirmed fixed in this release
