### ISSUE TITLE
I am trying to restore my ZEN from a backup file - Getting Cannot Decrypt File

### ISSUE THREAD

**Issue by Timmmer2** [ZencashOfficial/arizen#397]
**Describe the bug**
My PC drive crashed. I am trying to restore my ZEN in Arizen from a backup using the exact same version that was installed - Arizen 1.2.0

**To Reproduce**
I follow the process of creating a new login name after installation, and then at the bottom I point to the backup file and input the original user name and password. No matter which one of the three backups I choose, I always get "cannot decrypt file" on bottom right. I have tried backups off of a USB stick, my NAS and an external drive.

**Expected behavior**
I find it implausible that every copy of my Backups on on three media are corrupt. I have read and followed the process so this should work.  I even tried to create a new account and then import the data. This appears to work. However, after refreshing the data, there are  zero coins.

**Please complete the following information:**
Windows 10 64bit latest updates installed

**Additional context**

**Comment by Timmmer2** [comment]
I tried the latest version of Arizen with the same results.

**Comment by zennermac** [comment]
Hi @Timmmer2 

I would encourage you to open a ticket on the service desk https://support.horizen.global
We have a team on hand 24/7 for just this type of issue.
Please let me know your ticket number and I can assign to the relevant team member to take you through the process of debugging this.

**Comment by Timmmer2** [comment]
I was able to recover the coins eventually through trial and error.
Thank you
