### ISSUE TITLE
Add destination address to Transaction History list along with an export

### ISSUE THREAD

**Issue by ADumaine** [ZencashOfficial/arizen#405]
**Is your feature request related to a problem? Please describe.**
Inability to see the To address without clicking on the line.

**Describe the solution you'd like**
Add the To address between the date and the amount

![image](https://user-images.githubusercontent.com/1069218/55448831-341bfb00-557e-11e9-8acf-6c667c52da5f.png)

This would be similar to the swing wallet which already has the destination address in the history list.

Other suggestions:

- ability to export the list of transactions.  Ideally given a date range.
- ability to filter the Transaction History. Click on an address in the left panel to filter on just that address. Click on Transaction History or a Reset button to show all.

Perhaps these features could be part of an Advanced mode enabled in the settings.

**Comment by cronicc** [comment]
Arizen is in pure maintenance mode, no new features will be implemented. Only critical bug fixes and dependency management are being done.
