### ISSUE TITLE
Arizen wallet API URLs are not working

### ISSUE THREAD

**Issue by javajox** [ZencashOfficial/arizen#414]
Arizen wallet not working

1.Login into wallet
2.Press "Refresh" button
3.Nothing happens

After a little investigation I've found out that the following URLs are not working:
https://explorer.zensystem.io/insight-api-zen
https://explorer.zen-solutions.io/api
http://explorer.zenmine.pro/insight-api-zen

Version - 
Arizen - 1.2.3
Os - Ubuntu 18.04.2 LTS x64

**Comment by javajox** [comment]
It started to work today, anyway it is not stable, sometimes it fail to refresh

**Comment by vherus** [comment]
Hi @javajox 

Apologies for the late response. Those links are outdated so you'll need to update them manually, I recommend using `https://explorer.zensystem.io/api`

I'll update this in Arizen so the next release will resolve this issue.

**Comment by javajox** [comment]
@vherus, it started to work with the new URL. Please keep the Linux version of wallet working. The community need Linux support.
Thanks!

**Comment by Sto1cNate** [comment]
@zennermac I think we can close this issue.
