### ISSUE TITLE
iOS version?

### ISSUE THREAD

**Issue by kennym** [ZencashOfficial/arizen#427]
In the README is a screenshot of push notifications via iOS - does this mean there is an iOS app planned? If yes, how can I test that?

**Comment by psyraxaus** [comment]
Hello Kenny,

No they are not screen shots of push notifications on iOS.  They are notifications in the MacOS notification centre.  There are no plans for Arizen to be on iOS.

**Comment by kennym** [comment]
Got it! Thanks!
