### ISSUE TITLE
Can't login to Arizen Wallet

### ISSUE THREAD

**Issue by derb540** [ZencashOfficial/arizen#431]
For the last few days I am unable to login to Arizen Wallet
I enter my username and pw and nothing happens just sits on login screen.
The user name and PW are correct as I had written them down when I created the wallet.
Tried to restore from back up files but that doesn't do anything
I have uninstalled and reinstalled several times restarted windows but nothing seems to work.
Any help would be appreciated.
Thanks

.

**Comment by zennermac** [comment]
Hey there

What version of the wallet are you using, I am assuming its v1.2.4. 
Can you confirm?

**Comment by derb540** [comment]
Yes v1.2.4

**Comment by zennermac** [comment]
I think it may be better to move this to our [helpdesk](https://support.horizen.global) as we may need to dig into logs etc and we can more easily link you to any relevant documentation.

I can either open a ticket for you but I would need your email address for that, or you can just raise a ticket directly with no sign up required at the above link and I will look out for it. One of the helpdesk agents will be assigned etc.

**Comment by derb540** [comment]
OK thanks I will open a ticket

**Comment by zennermac** [comment]
Many thanks

Im looking out for it

**Comment by zennermac** [comment]
just responded to your ticket, one of the support team will be in touch with you.

**Comment by zennermac** [comment]
Can I close this Github Issue out now as we have moved to the Helpdesk?

**Comment by derb540** [comment]
Yes go ahead and close it.
Thanks

**Comment by derb540** [comment]
Thanks zennermac
