### ISSUE TITLE
Start using PGP keys to verify commits are coming from you:

### ISSUE THREAD

**Issue by aayanl** [ZencashOfficial/arizen#53]
^^
Instructions: 
https://help.github.com/articles/signing-commits-using-gpg/ 
https://git-scm.com/book/en/v2/Git-Tools-Signing-Your-Work

When done: Add your PUBLIC key to https://github.com/zencashofficial/keys via a pull request, make sure the commit is signed ^^

The reason being is that pgp signed commits verify that you indeed wrote the code otherwise this would happen https://github.com/jayphelps/git-blame-someone-else/commit/e5cfe4bb2190a2ae406d5f0b8f49c32ac0f01cd7

**Comment by LukasBures** [comment]
Thank you, we will do that asap :)

**Comment by LukasBures** [comment]
I have set my PGP key verification.

I am waiting for @neduchal and @jiri-novotny - after that, we can close this.

**Comment by aayanl** [comment]
Awesome :+1:

**Comment by LukasBures** [comment]
Now we are waiting for @neduchal  ... go go Petr 🥇

**Comment by LukasBures** [comment]
@neduchal has started to use PGP key - so we are waiting for he update  https://github.com/zencashofficial/keys and we are done 👍

**Comment by LukasBures** [comment]
All PGPs keys were added ...
