### ISSUE TITLE
Planned features for v2.0.0 version

### ISSUE THREAD

**Issue by LukasBures** [ZencashOfficial/arizen#72]
# Planned features for v2.0.0 version

## Bugs
- [ ] bug-free
- [ ] flawless `wallet.dat` import, when is file parsed there is chance that all addresses are not imported

## Missing features
Features which miss in current development branch:
- [x] Setting page, where all settings will be stored (e.g.: language, API, insight, number of transaction in displayed transaction history)
- [x] About page with contributors credits, license, and Arizen's version
- [x] Selector of user's addresses in sections: "From", "To"
- [x] Transaction history is too verbose, clickable transaction detail missing
- [x] Synchronise appearance of all buttons/menus/login page and etc 
- [x] Synchronise fonts
- [ ] Add functionality to add "known/friends/recently used" addresses to user's contact list

## Features (ordered by importance):
---
- [ ] **Reimplement our storage files**
1. Backward compatibility is MUST HAVE (implement import function)
2. Reimplement our storage files based on #115 
---
- [x] **new GUI for v1.1.0 - fully responsive and scalable**
---
- [x] **Add support for importing "exported file"**
1.  from Swing wallet
2. `*.awd` and `*.uawd`
3. plain text for PKs
---
- [x] **Option for withdrawing all funds for all of your Security Nodes which are > 42 ZEN**
1. Add to menu page/tab/navigation to a screen with: list of all addresses which user has in the wallet, then let user check checkbox (one checkbox per line, per address). The user will select the addresses which are used for Security Node staking (user has there at least 42.0 ZEN).
2. That list should be a table with lines, on each line will be **Name** (or address when the name was not set), **amount** of ZEN in that address, the **checkbox** for selecting processing.
3. Information about selecting/checking that address will be stored in local DB.
4. Next, there will be label/name of address/address hash (or blank at the beginning), next to this label will be button which call screen where you will be able to select one of your address where all the funds which met the condition will be sent.
5. At the bottom of this screen will be processing button "withdraw all funds greater than 42ZEN from all staking addresses". 
---
- [x] **Add option for selecting language to settings screen**
1. Add a dropdown list to the setting screen, where the user can set his preferred language.
---
- [x] **Generating paper wallet**
1. Add to menu page/tab/navigation to a screen with a possibility to generate new paper wallet with all necessary QR codes and the button for export to `*.pdf` file which user can print.
---
- [ ] **RPC connect user's Security Node**
1. Add to menu page/tab/navigation to a screen with a possibility to set all necessary parameters for connecting to user's Security Node.
---
- [ ] **Manage user's Security Node**
1. User could be able to manage his Security Node (it is based on **RPC connect user's Security Node**)- will be clarified
---
- [ ] **Sending private transaction**
---
- [ ] **Generating new private address**
---
- [ ] **Messenger**
0. It is based on: **RPC connect user's Security Node** and **Manage user's Security Node**
1. create, manage, add your identity
2. messaging 1-1
3. messaging 1-many
4. add/remove/edit your contacts
5. messaging history
6. compatible messaging with other messengers
---
- [ ] **HW wallet (TREZOR or Ledger Nano S) support**
---

**Comment by fungic** [comment]
| Option for withdrawing all funds for all of your Security Nodes which are > 42 ZEN

Please yes .. can't wait.

**Comment by LukasBures** [comment]
#304 is for actual roadmap
