### ISSUE TITLE
Register form - wrong working request in username (Windows)

### ISSUE THREAD

**Issue by Tigger1** [ZencashOfficial/arizen#80]
Testing was done on: Windows 7
Arizen version: 0.1.0-beta

Register form doesn't work properly. At first it is necessary to write a username with at least four letters. The requsted is highlighted by red color. See picture bellow.

![zen_first](https://user-images.githubusercontent.com/32774850/31577586-bf56a34a-b111-11e7-97db-2ba0f691e79b.png)

**But if it is written only 1 letter, the statement has been changed to green to indicate that the username is correct.** See picture bellow.

![zen_3](https://user-images.githubusercontent.com/32774850/31577529-9e177d54-b110-11e7-9b65-f01411c3bf4d.png)

**Comment by jiri-novotny** [comment]
fixed in 3ea11557d4a8de739c15fe27cd5fc7f4dda3c096
