### ISSUE TITLE
Register form - incorrect statement (Windows)

### ISSUE THREAD

**Issue by Tigger1** [ZencashOfficial/arizen#81]
Testing was done on: Windows 7
Arizen version: 0.1.0-beta

The username is supposed to have at least 4 letters. **If it is chosen username with 4, 5 and more letter the statement is highlighted by red color to indicate a wrong choise.** See pictures below.

![zen_4](https://user-images.githubusercontent.com/32774850/31578364-1678a85e-b120-11e7-8b4d-595e38c46d3f.png)

![zen_5](https://user-images.githubusercontent.com/32774850/31578325-2ed1e272-b11f-11e7-8088-7a36b7cd4279.PNG)

**Comment by jiri-novotny** [comment]
fixed in 3ea11557d4a8de739c15fe27cd5fc7f4dda3c096
