### ISSUE TITLE
Renaming of wallet (Windows)

### ISSUE THREAD

**Issue by Tigger1** [ZencashOfficial/arizen#83]
Testing was done on: Windows 7
Arizen version: 0.1.0-beta

It is possible to rename a wallet. After confirmation there is a statement "Wallet name has been updated". **Nevetheless in the list of wallets there is no change.** The user has to click on messenger and then back to wallet. After this the name of wallet is really updated. See picture below.

![zen_14](https://user-images.githubusercontent.com/32774850/31578512-0e0a3e1e-b123-11e7-9f02-f15980c81bb6.png)

**Comment by jiri-novotny** [comment]
Fixed in d8df922c03a29c5472217a86514d7a796ab2fefa
