### ISSUE TITLE
Transaction details - scroll bar (Windows)

### ISSUE THREAD

**Issue by Tigger1** [ZencashOfficial/arizen#84]
Testing was done on: Windows 7
Arizen version: 0.1.0-beta

**In the transaction details there is an extra scroll bar.** See picture below with highlighted bubble.

![zen_17](https://user-images.githubusercontent.com/32774850/31578615-fb835e36-b124-11e7-92ba-a8a8b2374823.png)

**Comment by neduchal** [comment]
Fixed in #78
