### ISSUE TITLE
Sending in wallet (Windows)

### ISSUE THREAD

**Issue by Tigger1** [ZencashOfficial/arizen#85]
Testing was done on: Windows 7
Arizen version: 0.1.0-beta

- In section "Send" there are different fonts.

- Destination wallet can be choosen in an address format. User cannot chose even his/her wallet.

See picture below with red arrows.

![zen_18](https://user-images.githubusercontent.com/32774850/31578706-2590d2d8-b127-11e7-805d-6d160e7d431f.png)

**Comment by jiri-novotny** [comment]
font was fixed in 1.0.0
destination button will be added in issue #87
