### ISSUE TITLE
Sending in wallet - tooltips (Windows)

### ISSUE THREAD

**Issue by Tigger1** [ZencashOfficial/arizen#86]
Testing was done on: Windows 7
Arizen version: 0.1.0-beta

**It would be very usefull to add tooltips to the section "Send".** See picture below with a red bubble.

![zen_19](https://user-images.githubusercontent.com/32774850/31578859-06674d26-b12a-11e7-8c89-18d262b19262.png)

**Comment by jiri-novotny** [comment]
this was added in 1.0.0
