### ISSUE TITLE
Feature for a wallet - sending (Windows)

### ISSUE THREAD

**Issue by Tigger1** [ZencashOfficial/arizen#87]
Testing was done on: Windows 7
Arizen version: 0.1.0-beta

If user wants to send to a destination wallet ("To"), the wallet can be chosen only in address format. It would be more user friendly to have an option "Select", too (just to choose from a list of favourite wallets e.g. wallet of your wife, girlfriend, etc. :-D ).
See picture below with a red box.

![zen_20](https://user-images.githubusercontent.com/32774850/31579044-84dc6a6c-b12d-11e7-8a9d-c9ed19daf6c9.png)

**Comment by Tigger1** [comment]
Still not implemented in v1.0.0. 
Pending for correction.
Thank you:-)

**Comment by LukasBures** [comment]
postponing to v2.0.0 version

**Comment by LukasBures** [comment]
Selecting from own addresses was added in b4a34ee854469c0d0378000759c6616307cbe9ec will be added in #111 v1.0.1

**Comment by LukasBures** [comment]
The functionality of addind "known/friends" addresses is still not implemented

**Comment by LukasBures** [comment]
The functionality of adding "known/friends" will be implemented in #72
