### ISSUE TITLE
Transaction history missing (Windows)

### ISSUE THREAD

**Issue by Tigger1** [ZencashOfficial/arizen#95]
Testing was done on: Windows 7
Arizen version: 1.0.0

If user log in to the wallet there is no transaction history. Clicking on "Refresh" button doesn't help. See picture below.

![1](https://user-images.githubusercontent.com/32774850/31854152-41d86d66-b695-11e7-8243-21347ca4a03b.PNG)

**Comment by LukasBures** [comment]
Try to change settings
![snimek obrazovky 2017-10-21 v 19 39 04](https://user-images.githubusercontent.com/3979946/31854331-96489612-b697-11e7-9c3c-67008e38662c.png)

**Comment by Tigger1** [comment]
Despite of having the same setting it doesn't work :-( See pics below.


![3](https://user-images.githubusercontent.com/32774850/31854399-9e88f672-b698-11e7-9426-154cb6bb22c0.PNG)
![2](https://user-images.githubusercontent.com/32774850/31854404-b03e5358-b698-11e7-9815-a966839ebb72.PNG)

**Comment by jiri-novotny** [comment]
Make it http only

**Comment by jiri-novotny** [comment]
Make it http only

**Comment by LukasBures** [comment]
It was down ?

![snimek obrazovky 2017-10-21 v 20 56 54](https://user-images.githubusercontent.com/3979946/31855012-67e34d48-b6a2-11e7-8c0b-0197312e40d0.png)

**Comment by LukasBures** [comment]
This works
![snimek obrazovky 2017-10-21 v 20 58 17](https://user-images.githubusercontent.com/3979946/31855020-947d9cbe-b6a2-11e7-93fa-e141670f9ddb.png)

**Comment by LukasBures** [comment]
Old transactions still doesnt apear ... :/

**Comment by Tigger1** [comment]
@jiri-novotny : I tried even http only - doesn't work:-(

**Comment by Tigger1** [comment]
Problem fixed in version 1.0.0
