### ISSUE TITLE
User cannot register

### ISSUE THREAD

**Issue by Tigger1** [ZencashOfficial/arizen#97]
Arizen version: 0.1.0-beta

Somebody from Slack cannot even register, see pic below:
![pasted image at 2017_10_20 03_37 pm](https://user-images.githubusercontent.com/32774850/31854612-5741e5c2-b69c-11e7-8dde-b7f076fee86a.png)

**Comment by LukasBures** [comment]
Just a note: that was Windows OS

**Comment by jiri-novotny** [comment]
cannot reproduce in 8892b59171b355b0990ce6e3e21d6381b62967ee

**Comment by Tigger1** [comment]
Fixed in v1.0.0 for W7.
Thank you :+1:
