### ISSUE TITLE
Can't send transaction

### ISSUE THREAD

**Issue by momentmaker** [ZencashOfficial/arizen#99]
When I tried to send and using the select button to select the wallet.

It's not letting me send because of this error:

`Bad format of source address!`

I think it's because it's getting the wallet's name instead of the address because the name is displayed instead of the address.

I'm using MacOSX.

**Comment by Tigger1** [comment]
Fixed in b60069d

**Comment by Tigger1** [comment]
It will be fixed in the next release (CW 43).
